/* ── Push — Mock Location Data (6 NYC Stores) ───────────────────────────── */

export type LocationStatus = "open" | "closed";

export type QRCode = {
  id: string;
  label: string;
  scans_today: number;
  scans_total: number;
  active: boolean;
};

export type StaffMember = {
  id: string;
  name: string;
  role: string;
  on_shift: boolean;
  avatar_seed: string;
};

export type BusinessHours = {
  day: string;
  open: string;
  close: string;
  closed: boolean;
};

export type CampaignHistoryItem = {
  id: string;
  title: string;
  status: "active" | "closed" | "paused";
  creators: number;
  scans: number;
  revenue: number;
  period: string;
};

export type POSIntegration = {
  name: "Square" | "Toast" | "Clover";
  connected: boolean;
  last_sync?: string;
};

export type Location = {
  id: string;
  merchant_id: string;
  tenant_id: string;
  name: string;
  business_name: string;
  neighborhood: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  lat: number;
  lng: number;
  status: LocationStatus;
  image_url: string;
  phone: string;
  email: string;
  // Stats
  scans_7d: number;
  conversions_30d: number;
  staff_count: number;
  // Primary campaign
  primary_campaign_title: string | null;
  primary_campaign_status: "active" | "paused" | "closed" | null;
  // Operations
  qr_codes: QRCode[];
  staff: StaffMember[];
  hours: BusinessHours[];
  campaign_history: CampaignHistoryItem[];
  pos_integrations: POSIntegration[];
  created_at: string;
};

const DEFAULT_HOURS: BusinessHours[] = [
  { day: "Monday", open: "08:00", close: "20:00", closed: false },
  { day: "Tuesday", open: "08:00", close: "20:00", closed: false },
  { day: "Wednesday", open: "08:00", close: "20:00", closed: false },
  { day: "Thursday", open: "08:00", close: "21:00", closed: false },
  { day: "Friday", open: "08:00", close: "22:00", closed: false },
  { day: "Saturday", open: "09:00", close: "22:00", closed: false },
  { day: "Sunday", open: "10:00", close: "18:00", closed: false },
];

export const MOCK_LOCATIONS: Location[] = [
  /* ─── 1. Bed-Stuy ─────────────────────────────────────────────── */
  {
    id: "loc-bed-stuy",
    merchant_id: "demo-merchant-001",
    tenant_id: "tenant-demo-001",
    name: "Blank Street — Bed-Stuy",
    business_name: "Blank Street Coffee - Bed-Stuy",
    neighborhood: "Bed-Stuy",
    address: "417 Tompkins Ave",
    city: "Brooklyn",
    state: "NY",
    zip: "11216",
    lat: 40.6834,
    lng: -73.9418,
    status: "open",
    image_url:
      "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800&q=80",
    phone: "(718) 555-0101",
    email: "bedstuy@blankstreet.com",
    scans_7d: 84,
    conversions_30d: 62,
    staff_count: 6,
    primary_campaign_title: "Brooklyn Morning Ritual",
    primary_campaign_status: "active",
    qr_codes: [
      {
        id: "qr-bs-1",
        label: "Front Counter",
        scans_today: 12,
        scans_total: 341,
        active: true,
      },
      {
        id: "qr-bs-2",
        label: "Window Seat",
        scans_today: 7,
        scans_total: 198,
        active: true,
      },
      {
        id: "qr-bs-3",
        label: "To-Go Station",
        scans_today: 4,
        scans_total: 112,
        active: true,
      },
    ],
    staff: [
      {
        id: "s-bs-1",
        name: "Marcus Webb",
        role: "Manager",
        on_shift: true,
        avatar_seed: "MarcusWebb",
      },
      {
        id: "s-bs-2",
        name: "Jade Rivera",
        role: "Barista",
        on_shift: true,
        avatar_seed: "JadeRivera",
      },
      {
        id: "s-bs-3",
        name: "Eli Thornton",
        role: "Barista",
        on_shift: false,
        avatar_seed: "EliThornton",
      },
      {
        id: "s-bs-4",
        name: "Zoe Nakamura",
        role: "Barista",
        on_shift: true,
        avatar_seed: "ZoeNakamura",
      },
      {
        id: "s-bs-5",
        name: "Omar Hassan",
        role: "Cashier",
        on_shift: false,
        avatar_seed: "OmarHassan",
      },
      {
        id: "s-bs-6",
        name: "Priya Mehta",
        role: "Barista",
        on_shift: true,
        avatar_seed: "PriyaMehta",
      },
    ],
    hours: DEFAULT_HOURS,
    campaign_history: [
      {
        id: "ch-bs-1",
        title: "Brooklyn Morning Ritual",
        status: "active",
        creators: 5,
        scans: 84,
        revenue: 1840,
        period: "Apr 2026",
      },
      {
        id: "ch-bs-2",
        title: "Spring Latte Launch",
        status: "closed",
        creators: 4,
        scans: 121,
        revenue: 2310,
        period: "Mar 2026",
      },
      {
        id: "ch-bs-3",
        title: "Valentine's Day Special",
        status: "closed",
        creators: 3,
        scans: 97,
        revenue: 1920,
        period: "Feb 2026",
      },
      {
        id: "ch-bs-4",
        title: "New Year Cold Brew",
        status: "closed",
        creators: 6,
        scans: 154,
        revenue: 2680,
        period: "Jan 2026",
      },
      {
        id: "ch-bs-5",
        title: "Holiday Blend Reveal",
        status: "closed",
        creators: 4,
        scans: 88,
        revenue: 1740,
        period: "Dec 2025",
      },
      {
        id: "ch-bs-6",
        title: "Cozy Autumn Drinks",
        status: "closed",
        creators: 3,
        scans: 73,
        revenue: 1210,
        period: "Nov 2025",
      },
      {
        id: "ch-bs-7",
        title: "Pumpkin Season Push",
        status: "closed",
        creators: 5,
        scans: 108,
        revenue: 1980,
        period: "Oct 2025",
      },
      {
        id: "ch-bs-8",
        title: "Back to School Fuel",
        status: "closed",
        creators: 4,
        scans: 91,
        revenue: 1640,
        period: "Sep 2025",
      },
      {
        id: "ch-bs-9",
        title: "Summer Refresh Series",
        status: "closed",
        creators: 6,
        scans: 133,
        revenue: 2200,
        period: "Aug 2025",
      },
      {
        id: "ch-bs-10",
        title: "Grand Opening Week",
        status: "closed",
        creators: 8,
        scans: 201,
        revenue: 3100,
        period: "Jul 2025",
      },
    ],
    pos_integrations: [
      { name: "Square", connected: true, last_sync: "2026-04-17T09:15:00Z" },
      { name: "Toast", connected: false },
      { name: "Clover", connected: false },
    ],
    created_at: "2025-07-01T08:00:00Z",
  },

  /* ─── 2. Williamsburg ─────────────────────────────────────────── */
  {
    id: "loc-williamsburg",
    merchant_id: "demo-merchant-001",
    tenant_id: "tenant-demo-001",
    name: "Blank Street — Williamsburg",
    business_name: "Blank Street Coffee - Williamsburg",
    neighborhood: "Williamsburg",
    address: "119 N 7th St",
    city: "Brooklyn",
    state: "NY",
    zip: "11249",
    lat: 40.7199,
    lng: -73.957,
    status: "open",
    image_url:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    phone: "(718) 555-0202",
    email: "williamsburg@blankstreet.com",
    scans_7d: 112,
    conversions_30d: 89,
    staff_count: 8,
    primary_campaign_title: "Williamsburg Art Week",
    primary_campaign_status: "active",
    qr_codes: [
      {
        id: "qr-wm-1",
        label: "Main Bar",
        scans_today: 18,
        scans_total: 502,
        active: true,
      },
      {
        id: "qr-wm-2",
        label: "Back Lounge",
        scans_today: 9,
        scans_total: 287,
        active: true,
      },
      {
        id: "qr-wm-3",
        label: "Sidewalk Table",
        scans_today: 11,
        scans_total: 341,
        active: true,
      },
      {
        id: "qr-wm-4",
        label: "Merch Display",
        scans_today: 3,
        scans_total: 89,
        active: false,
      },
    ],
    staff: [
      {
        id: "s-wm-1",
        name: "Sasha Bloom",
        role: "Manager",
        on_shift: true,
        avatar_seed: "SashaBloom",
      },
      {
        id: "s-wm-2",
        name: "Dev Kapoor",
        role: "Barista",
        on_shift: true,
        avatar_seed: "DevKapoor",
      },
      {
        id: "s-wm-3",
        name: "Mia Torres",
        role: "Barista",
        on_shift: true,
        avatar_seed: "MiaTorres",
      },
      {
        id: "s-wm-4",
        name: "Luca Ferrara",
        role: "Cashier",
        on_shift: false,
        avatar_seed: "LucaFerrara",
      },
      {
        id: "s-wm-5",
        name: "Nadia Okonkwo",
        role: "Barista",
        on_shift: true,
        avatar_seed: "NadiaOkonkwo",
      },
      {
        id: "s-wm-6",
        name: "Tom Wu",
        role: "Barista",
        on_shift: false,
        avatar_seed: "TomWu",
      },
      {
        id: "s-wm-7",
        name: "Ana Silva",
        role: "Barista",
        on_shift: true,
        avatar_seed: "AnaSilva",
      },
      {
        id: "s-wm-8",
        name: "Ben Carter",
        role: "Manager",
        on_shift: false,
        avatar_seed: "BenCarter",
      },
    ],
    hours: [
      { day: "Monday", open: "07:00", close: "21:00", closed: false },
      { day: "Tuesday", open: "07:00", close: "21:00", closed: false },
      { day: "Wednesday", open: "07:00", close: "21:00", closed: false },
      { day: "Thursday", open: "07:00", close: "22:00", closed: false },
      { day: "Friday", open: "07:00", close: "23:00", closed: false },
      { day: "Saturday", open: "08:00", close: "23:00", closed: false },
      { day: "Sunday", open: "09:00", close: "20:00", closed: false },
    ],
    campaign_history: [
      {
        id: "ch-wm-1",
        title: "Williamsburg Art Week",
        status: "active",
        creators: 7,
        scans: 112,
        revenue: 2640,
        period: "Apr 2026",
      },
      {
        id: "ch-wm-2",
        title: "Spring Outdoor Sessions",
        status: "closed",
        creators: 5,
        scans: 142,
        revenue: 2890,
        period: "Mar 2026",
      },
      {
        id: "ch-wm-3",
        title: "Indie Market Weekend",
        status: "closed",
        creators: 6,
        scans: 118,
        revenue: 2340,
        period: "Feb 2026",
      },
      {
        id: "ch-wm-4",
        title: "Cold Brew Season Opener",
        status: "closed",
        creators: 8,
        scans: 189,
        revenue: 3210,
        period: "Jan 2026",
      },
      {
        id: "ch-wm-5",
        title: "Holiday Pop-Up Series",
        status: "closed",
        creators: 6,
        scans: 157,
        revenue: 2870,
        period: "Dec 2025",
      },
      {
        id: "ch-wm-6",
        title: "Film Festival Collab",
        status: "closed",
        creators: 4,
        scans: 98,
        revenue: 1840,
        period: "Nov 2025",
      },
      {
        id: "ch-wm-7",
        title: "Spooky Sips Campaign",
        status: "closed",
        creators: 5,
        scans: 121,
        revenue: 2190,
        period: "Oct 2025",
      },
      {
        id: "ch-wm-8",
        title: "Back to School Special",
        status: "closed",
        creators: 7,
        scans: 134,
        revenue: 2450,
        period: "Sep 2025",
      },
      {
        id: "ch-wm-9",
        title: "NYC Summer Hustle",
        status: "closed",
        creators: 9,
        scans: 201,
        revenue: 3640,
        period: "Aug 2025",
      },
      {
        id: "ch-wm-10",
        title: "Soft Open Week",
        status: "closed",
        creators: 10,
        scans: 244,
        revenue: 4100,
        period: "Jul 2025",
      },
    ],
    pos_integrations: [
      { name: "Square", connected: true, last_sync: "2026-04-17T08:40:00Z" },
      { name: "Toast", connected: true, last_sync: "2026-04-17T08:40:00Z" },
      { name: "Clover", connected: false },
    ],
    created_at: "2025-07-15T09:00:00Z",
  },

  /* ─── 3. Chelsea ──────────────────────────────────────────────── */
  {
    id: "loc-chelsea",
    merchant_id: "demo-merchant-001",
    tenant_id: "tenant-demo-001",
    name: "Blank Street — Chelsea",
    business_name: "Blank Street Coffee - Chelsea",
    neighborhood: "Chelsea",
    address: "184 8th Ave",
    city: "New York",
    state: "NY",
    zip: "10011",
    lat: 40.743,
    lng: -74.0014,
    status: "open",
    image_url:
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
    phone: "(212) 555-0303",
    email: "chelsea@blankstreet.com",
    scans_7d: 67,
    conversions_30d: 48,
    staff_count: 5,
    primary_campaign_title: "Gallery District Reels",
    primary_campaign_status: "paused",
    qr_codes: [
      {
        id: "qr-ch-1",
        label: "Counter QR",
        scans_today: 8,
        scans_total: 223,
        active: true,
      },
      {
        id: "qr-ch-2",
        label: "Loyalty Card",
        scans_today: 5,
        scans_total: 178,
        active: true,
      },
      {
        id: "qr-ch-3",
        label: "Window Decal",
        scans_today: 2,
        scans_total: 67,
        active: false,
      },
    ],
    staff: [
      {
        id: "s-ch-1",
        name: "Frances Bell",
        role: "Manager",
        on_shift: true,
        avatar_seed: "FrancesBell",
      },
      {
        id: "s-ch-2",
        name: "Ray Ortega",
        role: "Barista",
        on_shift: true,
        avatar_seed: "RayOrtega",
      },
      {
        id: "s-ch-3",
        name: "Ines Dubois",
        role: "Barista",
        on_shift: false,
        avatar_seed: "InesDubois",
      },
      {
        id: "s-ch-4",
        name: "Cal Morris",
        role: "Cashier",
        on_shift: true,
        avatar_seed: "CalMorris",
      },
      {
        id: "s-ch-5",
        name: "Tara Singh",
        role: "Barista",
        on_shift: false,
        avatar_seed: "TaraSingh",
      },
    ],
    hours: DEFAULT_HOURS,
    campaign_history: [
      {
        id: "ch-ch-1",
        title: "Gallery District Reels",
        status: "paused",
        creators: 3,
        scans: 67,
        revenue: 1240,
        period: "Apr 2026",
      },
      {
        id: "ch-ch-2",
        title: "Chelsea Market Collab",
        status: "closed",
        creators: 5,
        scans: 93,
        revenue: 1780,
        period: "Mar 2026",
      },
      {
        id: "ch-ch-3",
        title: "Date Night Coffee",
        status: "closed",
        creators: 4,
        scans: 81,
        revenue: 1520,
        period: "Feb 2026",
      },
      {
        id: "ch-ch-4",
        title: "Winter Warmers",
        status: "closed",
        creators: 3,
        scans: 72,
        revenue: 1340,
        period: "Jan 2026",
      },
      {
        id: "ch-ch-5",
        title: "Holiday Gift Campaign",
        status: "closed",
        creators: 4,
        scans: 88,
        revenue: 1640,
        period: "Dec 2025",
      },
      {
        id: "ch-ch-6",
        title: "Fashion Week Fuel",
        status: "closed",
        creators: 6,
        scans: 142,
        revenue: 2640,
        period: "Nov 2025",
      },
      {
        id: "ch-ch-7",
        title: "Art Basel Preview",
        status: "closed",
        creators: 5,
        scans: 113,
        revenue: 2100,
        period: "Oct 2025",
      },
      {
        id: "ch-ch-8",
        title: "September Editorial",
        status: "closed",
        creators: 4,
        scans: 98,
        revenue: 1840,
        period: "Sep 2025",
      },
      {
        id: "ch-ch-9",
        title: "High Summer Sessions",
        status: "closed",
        creators: 5,
        scans: 107,
        revenue: 2010,
        period: "Aug 2025",
      },
      {
        id: "ch-ch-10",
        title: "Opening Week",
        status: "closed",
        creators: 7,
        scans: 178,
        revenue: 3100,
        period: "Jul 2025",
      },
    ],
    pos_integrations: [
      { name: "Square", connected: false },
      { name: "Toast", connected: true, last_sync: "2026-04-17T07:55:00Z" },
      { name: "Clover", connected: false },
    ],
    created_at: "2025-08-01T10:00:00Z",
  },

  /* ─── 4. LES ──────────────────────────────────────────────────── */
  {
    id: "loc-les",
    merchant_id: "demo-merchant-001",
    tenant_id: "tenant-demo-001",
    name: "Blank Street — Lower East Side",
    business_name: "Blank Street Coffee - Lower East Side",
    neighborhood: "Lower East Side",
    address: "88 Orchard St",
    city: "New York",
    state: "NY",
    zip: "10002",
    lat: 40.7178,
    lng: -73.9897,
    status: "open",
    image_url:
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80",
    phone: "(212) 555-0404",
    email: "les@blankstreet.com",
    scans_7d: 53,
    conversions_30d: 37,
    staff_count: 4,
    primary_campaign_title: "LES Night Owls",
    primary_campaign_status: "active",
    qr_codes: [
      {
        id: "qr-les-1",
        label: "Bar Sticker",
        scans_today: 9,
        scans_total: 198,
        active: true,
      },
      {
        id: "qr-les-2",
        label: "Outdoor Sign",
        scans_today: 6,
        scans_total: 143,
        active: true,
      },
      {
        id: "qr-les-3",
        label: "Receipt QR",
        scans_today: 3,
        scans_total: 78,
        active: true,
      },
    ],
    staff: [
      {
        id: "s-les-1",
        name: "Danny Park",
        role: "Manager",
        on_shift: false,
        avatar_seed: "DannyPark",
      },
      {
        id: "s-les-2",
        name: "Coco Zhang",
        role: "Barista",
        on_shift: true,
        avatar_seed: "CocoZhang",
      },
      {
        id: "s-les-3",
        name: "Leo Reyes",
        role: "Barista",
        on_shift: true,
        avatar_seed: "LeoReyes",
      },
      {
        id: "s-les-4",
        name: "Sam Goldstein",
        role: "Cashier",
        on_shift: true,
        avatar_seed: "SamGoldstein",
      },
    ],
    hours: [
      { day: "Monday", open: "09:00", close: "22:00", closed: false },
      { day: "Tuesday", open: "09:00", close: "22:00", closed: false },
      { day: "Wednesday", open: "09:00", close: "22:00", closed: false },
      { day: "Thursday", open: "09:00", close: "23:00", closed: false },
      { day: "Friday", open: "09:00", close: "24:00", closed: false },
      { day: "Saturday", open: "10:00", close: "24:00", closed: false },
      { day: "Sunday", open: "10:00", close: "22:00", closed: false },
    ],
    campaign_history: [
      {
        id: "ch-les-1",
        title: "LES Night Owls",
        status: "active",
        creators: 4,
        scans: 53,
        revenue: 980,
        period: "Apr 2026",
      },
      {
        id: "ch-les-2",
        title: "Orchard St Buzz",
        status: "closed",
        creators: 3,
        scans: 78,
        revenue: 1420,
        period: "Mar 2026",
      },
      {
        id: "ch-les-3",
        title: "Valentine Late Hours",
        status: "closed",
        creators: 2,
        scans: 61,
        revenue: 1140,
        period: "Feb 2026",
      },
      {
        id: "ch-les-4",
        title: "Winter Bar Series",
        status: "closed",
        creators: 3,
        scans: 69,
        revenue: 1280,
        period: "Jan 2026",
      },
      {
        id: "ch-les-5",
        title: "Holiday Night Life",
        status: "closed",
        creators: 4,
        scans: 87,
        revenue: 1610,
        period: "Dec 2025",
      },
      {
        id: "ch-les-6",
        title: "Culture Festival Week",
        status: "closed",
        creators: 5,
        scans: 101,
        revenue: 1890,
        period: "Nov 2025",
      },
      {
        id: "ch-les-7",
        title: "Halloween Haunts",
        status: "closed",
        creators: 4,
        scans: 94,
        revenue: 1720,
        period: "Oct 2025",
      },
      {
        id: "ch-les-8",
        title: "September Streets",
        status: "closed",
        creators: 3,
        scans: 72,
        revenue: 1330,
        period: "Sep 2025",
      },
      {
        id: "ch-les-9",
        title: "Summer Nights Out",
        status: "closed",
        creators: 5,
        scans: 118,
        revenue: 2140,
        period: "Aug 2025",
      },
      {
        id: "ch-les-10",
        title: "Grand Opening",
        status: "closed",
        creators: 6,
        scans: 156,
        revenue: 2800,
        period: "Jul 2025",
      },
    ],
    pos_integrations: [
      { name: "Square", connected: true, last_sync: "2026-04-17T09:00:00Z" },
      { name: "Toast", connected: false },
      { name: "Clover", connected: false },
    ],
    created_at: "2025-07-20T11:00:00Z",
  },

  /* ─── 5. DUMBO ────────────────────────────────────────────────── */
  {
    id: "loc-dumbo",
    merchant_id: "demo-merchant-001",
    tenant_id: "tenant-demo-001",
    name: "Blank Street — DUMBO",
    business_name: "Blank Street Coffee - DUMBO",
    neighborhood: "DUMBO",
    address: "55 Water St",
    city: "Brooklyn",
    state: "NY",
    zip: "11201",
    lat: 40.7033,
    lng: -73.9885,
    status: "closed",
    image_url:
      "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&q=80",
    phone: "(718) 555-0505",
    email: "dumbo@blankstreet.com",
    scans_7d: 31,
    conversions_30d: 21,
    staff_count: 4,
    primary_campaign_title: "Brooklyn Bridge Views",
    primary_campaign_status: "closed",
    qr_codes: [
      {
        id: "qr-dm-1",
        label: "Entry Point",
        scans_today: 0,
        scans_total: 134,
        active: false,
      },
      {
        id: "qr-dm-2",
        label: "Photo Wall",
        scans_today: 0,
        scans_total: 98,
        active: true,
      },
    ],
    staff: [
      {
        id: "s-dm-1",
        name: "Iris Chen",
        role: "Manager",
        on_shift: false,
        avatar_seed: "IrisChen",
      },
      {
        id: "s-dm-2",
        name: "Jay Monroe",
        role: "Barista",
        on_shift: false,
        avatar_seed: "JayMonroe",
      },
      {
        id: "s-dm-3",
        name: "Kit Larson",
        role: "Barista",
        on_shift: false,
        avatar_seed: "KitLarson",
      },
      {
        id: "s-dm-4",
        name: "Vera Scott",
        role: "Cashier",
        on_shift: false,
        avatar_seed: "VeraScott",
      },
    ],
    hours: [
      { day: "Monday", open: "08:00", close: "18:00", closed: false },
      { day: "Tuesday", open: "08:00", close: "18:00", closed: false },
      { day: "Wednesday", open: "08:00", close: "18:00", closed: false },
      { day: "Thursday", open: "08:00", close: "18:00", closed: false },
      { day: "Friday", open: "08:00", close: "19:00", closed: false },
      { day: "Saturday", open: "09:00", close: "19:00", closed: false },
      { day: "Sunday", open: "10:00", close: "17:00", closed: false },
    ],
    campaign_history: [
      {
        id: "ch-dm-1",
        title: "Brooklyn Bridge Views",
        status: "closed",
        creators: 3,
        scans: 54,
        revenue: 980,
        period: "Mar 2026",
      },
      {
        id: "ch-dm-2",
        title: "DUMBO Arts District",
        status: "closed",
        creators: 4,
        scans: 72,
        revenue: 1310,
        period: "Feb 2026",
      },
      {
        id: "ch-dm-3",
        title: "Winter Waterfront",
        status: "closed",
        creators: 2,
        scans: 43,
        revenue: 780,
        period: "Jan 2026",
      },
      {
        id: "ch-dm-4",
        title: "Holiday Skyline",
        status: "closed",
        creators: 3,
        scans: 68,
        revenue: 1240,
        period: "Dec 2025",
      },
      {
        id: "ch-dm-5",
        title: "Autumn Light Series",
        status: "closed",
        creators: 4,
        scans: 81,
        revenue: 1490,
        period: "Nov 2025",
      },
      {
        id: "ch-dm-6",
        title: "Bridge Walk Campaign",
        status: "closed",
        creators: 3,
        scans: 67,
        revenue: 1220,
        period: "Oct 2025",
      },
      {
        id: "ch-dm-7",
        title: "September Sunsets",
        status: "closed",
        creators: 4,
        scans: 78,
        revenue: 1410,
        period: "Sep 2025",
      },
      {
        id: "ch-dm-8",
        title: "Summer Rooftop",
        status: "closed",
        creators: 5,
        scans: 99,
        revenue: 1780,
        period: "Aug 2025",
      },
      {
        id: "ch-dm-9",
        title: "Outdoor Cinema Nights",
        status: "closed",
        creators: 4,
        scans: 88,
        revenue: 1590,
        period: "Jul 2025",
      },
      {
        id: "ch-dm-10",
        title: "Launch Week",
        status: "closed",
        creators: 6,
        scans: 141,
        revenue: 2540,
        period: "Jun 2025",
      },
    ],
    pos_integrations: [
      { name: "Square", connected: false },
      { name: "Toast", connected: false },
      { name: "Clover", connected: true, last_sync: "2026-04-16T18:30:00Z" },
    ],
    created_at: "2025-06-01T12:00:00Z",
  },

  /* ─── 6. Bushwick ─────────────────────────────────────────────── */
  {
    id: "loc-bushwick",
    merchant_id: "demo-merchant-001",
    tenant_id: "tenant-demo-001",
    name: "Blank Street — Bushwick",
    business_name: "Blank Street Coffee - Bushwick",
    neighborhood: "Bushwick",
    address: "304 Wyckoff Ave",
    city: "Brooklyn",
    state: "NY",
    zip: "11237",
    lat: 40.7056,
    lng: -73.9219,
    status: "open",
    image_url:
      "https://images.unsplash.com/photo-1493857671505-72967e2e2760?w=800&q=80",
    phone: "(718) 555-0606",
    email: "bushwick@blankstreet.com",
    scans_7d: 76,
    conversions_30d: 54,
    staff_count: 5,
    primary_campaign_title: "Bushwick Collective Collab",
    primary_campaign_status: "active",
    qr_codes: [
      {
        id: "qr-bw-1",
        label: "Mural Wall",
        scans_today: 14,
        scans_total: 312,
        active: true,
      },
      {
        id: "qr-bw-2",
        label: "Counter Card",
        scans_today: 8,
        scans_total: 201,
        active: true,
      },
      {
        id: "qr-bw-3",
        label: "Outdoor Sticker",
        scans_today: 5,
        scans_total: 134,
        active: true,
      },
    ],
    staff: [
      {
        id: "s-bw-1",
        name: "Niko Vasquez",
        role: "Manager",
        on_shift: true,
        avatar_seed: "NikoVasquez",
      },
      {
        id: "s-bw-2",
        name: "Leila Patel",
        role: "Barista",
        on_shift: true,
        avatar_seed: "LeilaPatel",
      },
      {
        id: "s-bw-3",
        name: "Max Osei",
        role: "Barista",
        on_shift: false,
        avatar_seed: "MaxOsei",
      },
      {
        id: "s-bw-4",
        name: "Rosa Fuentes",
        role: "Barista",
        on_shift: true,
        avatar_seed: "RosaFuentes",
      },
      {
        id: "s-bw-5",
        name: "Jin Park",
        role: "Cashier",
        on_shift: false,
        avatar_seed: "JinPark",
      },
    ],
    hours: [
      { day: "Monday", open: "08:00", close: "21:00", closed: false },
      { day: "Tuesday", open: "08:00", close: "21:00", closed: false },
      { day: "Wednesday", open: "08:00", close: "21:00", closed: false },
      { day: "Thursday", open: "08:00", close: "22:00", closed: false },
      { day: "Friday", open: "08:00", close: "23:00", closed: false },
      { day: "Saturday", open: "09:00", close: "23:00", closed: false },
      { day: "Sunday", open: "09:00", close: "19:00", closed: false },
    ],
    campaign_history: [
      {
        id: "ch-bw-1",
        title: "Bushwick Collective Collab",
        status: "active",
        creators: 5,
        scans: 76,
        revenue: 1420,
        period: "Apr 2026",
      },
      {
        id: "ch-bw-2",
        title: "Street Art Trail",
        status: "closed",
        creators: 6,
        scans: 104,
        revenue: 1930,
        period: "Mar 2026",
      },
      {
        id: "ch-bw-3",
        title: "Underground Music Series",
        status: "closed",
        creators: 4,
        scans: 89,
        revenue: 1640,
        period: "Feb 2026",
      },
      {
        id: "ch-bw-4",
        title: "New Year Raw Energy",
        status: "closed",
        creators: 5,
        scans: 112,
        revenue: 2080,
        period: "Jan 2026",
      },
      {
        id: "ch-bw-5",
        title: "Winter Gallery Hop",
        status: "closed",
        creators: 4,
        scans: 97,
        revenue: 1790,
        period: "Dec 2025",
      },
      {
        id: "ch-bw-6",
        title: "Brooklyn Creator Fest",
        status: "closed",
        creators: 7,
        scans: 148,
        revenue: 2730,
        period: "Nov 2025",
      },
      {
        id: "ch-bw-7",
        title: "Halloween at the Mural",
        status: "closed",
        creators: 5,
        scans: 121,
        revenue: 2240,
        period: "Oct 2025",
      },
      {
        id: "ch-bw-8",
        title: "Back to Hustle",
        status: "closed",
        creators: 6,
        scans: 133,
        revenue: 2480,
        period: "Sep 2025",
      },
      {
        id: "ch-bw-9",
        title: "Summer Block Party",
        status: "closed",
        creators: 8,
        scans: 187,
        revenue: 3410,
        period: "Aug 2025",
      },
      {
        id: "ch-bw-10",
        title: "Opening Wave",
        status: "closed",
        creators: 9,
        scans: 221,
        revenue: 3890,
        period: "Jul 2025",
      },
    ],
    pos_integrations: [
      { name: "Square", connected: true, last_sync: "2026-04-17T08:20:00Z" },
      { name: "Toast", connected: false },
      { name: "Clover", connected: false },
    ],
    created_at: "2025-07-10T08:00:00Z",
  },
];

export function getLocationById(id: string): Location | undefined {
  return MOCK_LOCATIONS.find((l) => l.id === id);
}
