/**
 * Push v5.2 — Database row types
 *
 * TypeScript shapes for the six v5.2 tables created in /migrations/001-006.
 * One interface per table. No methods, no Supabase imports — pure data types
 * consumed by the lib/db helpers, the service layer, and API route handlers.
 *
 * Field-type conventions:
 *   - UUID  → string
 *   - DATE / TIMESTAMP / TIMESTAMPTZ → string (ISO 8601)
 *   - INT / DECIMAL → number
 *   - VARCHAR with CHECK constraint → string union (the allowed values)
 *   - Nullable SQL columns → `T | null`
 */

// ---------------------------------------------------------------------------
// 001_loyalty_cards
// ---------------------------------------------------------------------------

/**
 * Customer loyalty stamp card issued through a creator and redeemable at a
 * specific merchant. One card per (customer, merchant). Powers the
 * "推荐人卡" feature and the Creator Productivity Lock moat.
 */
export interface LoyaltyCard {
  /** Primary key (UUID). */
  id: string;
  /** UUID of the customer holding the card. */
  customer_id: string;
  /** UUID of the creator who issued the card (FK → creators.id). */
  creator_id: string;
  /** UUID of the redeeming merchant (FK → merchants.id). */
  merchant_id: string;
  /** Current number of stamps collected. Always 0 ≤ stamp_count ≤ max_stamps. */
  stamp_count: number;
  /** Stamps required to trigger redemption. Defaults to 10. */
  max_stamps: number;
  /** ISO timestamp when the card was redeemed; `null` while active. */
  redeemed_at: string | null;
  /** ISO timestamp when the row was inserted. */
  created_at: string;
  /** ISO timestamp of the last update. */
  updated_at: string;
}

// ---------------------------------------------------------------------------
// 002_ai_accuracy_audits
// ---------------------------------------------------------------------------

/**
 * Weekly snapshot of AI verification accuracy across the 3-layer pipeline
 * (QR + Vision OCR + geo-match). One row per ISO week. Drives the
 * ConversionOracle™ quality dashboard and the AI Accuracy KPI.
 */
export interface AIAccuracyAudit {
  /** Primary key (UUID). */
  id: string;
  /** ISO week number this audit covers (1..53). Unique per row. */
  week_number: number;
  /** Total claims auto-approved by the AI this week. */
  total_auto_verified: number;
  /** Auto-approved claims later overturned as fraudulent. */
  false_positive_count: number;
  /** Rejected/manual-review claims later confirmed legitimate via appeal. */
  false_negative_count: number;
  /** Percentage form of false_positive_count (0..100). */
  false_positive_rate: number;
  /** Percentage form of false_negative_count (0..100). */
  false_negative_rate: number;
  /** Claims sent to manual review and approved. */
  manual_approved: number;
  /** Claims sent to manual review and rejected. */
  manual_rejected: number;
  /** Number of creator appeals filed this week. */
  creator_appeals: number;
  /** Mean ai_confidence_score across all claims this week (0..100), or `null`. */
  average_confidence: number | null;
  /** ISO timestamp when this audit was generated. */
  audit_date: string;
  /** Free-form notes (root-cause analysis, anomalies, etc.). */
  notes: string | null;
  /** ISO timestamp when the row was inserted. */
  created_at: string;
  /** ISO timestamp of the last update. */
  updated_at: string;
}

// ---------------------------------------------------------------------------
// 003_merchant_metrics_weekly
// ---------------------------------------------------------------------------

/**
 * Pre-aggregated weekly KPIs per merchant. One row per (merchant, week_start).
 * Generated by WeeklyMerchantReportService and consumed by the merchant
 * dashboard and the Monday-morning weekly email.
 */
export interface MerchantMetricsWeekly {
  /** Primary key (UUID). */
  id: string;
  /** UUID of the merchant (FK → merchants.id). */
  merchant_id: string;
  /** Inclusive ISO date (YYYY-MM-DD) of the week's start, typically Monday. */
  week_start: string;
  /** Exclusive ISO date (YYYY-MM-DD) of the week's end. */
  week_end: string;
  /** Distinct customers verified for this merchant during the week. */
  verified_customers: number;
  /** Total revenue in USD attributed to verified customers this week. */
  total_revenue: number;
  /** Return on investment as a percentage: (revenue - cost) / cost * 100. */
  roi: number;
  /** Distinct creators that drove at least one verified customer this week. */
  creator_count: number;
  /** Mean transaction value (total_revenue / verified_customers) in USD. */
  average_transaction: number;
  /** ISO timestamp when the row was inserted. */
  created_at: string;
  /** ISO timestamp of the last update. */
  updated_at: string;
}

// ---------------------------------------------------------------------------
// 004_creator_recruitment_funnel
// ---------------------------------------------------------------------------

/** Recruitment tier: 1 = direct network, 2 = community, 3 = incentive prospect. */
export type CreatorTier = 1 | 2 | 3;

/** Lifecycle state in the recruitment funnel. */
export type CreatorRecruitmentStatus =
  | "prospect"
  | "early_operator"
  | "active"
  | "churn";

/** How the creator entered the funnel. */
export type CreatorRecruitmentSource =
  | "direct_network"
  | "community"
  | "incentive";

/**
 * Tracks each creator's position in Push's recruitment funnel: tier,
 * lifecycle status, source, and rolling performance score. One row per
 * creator. Implements Two-Segment Creator Economics from v5.1/v5.2.
 */
export interface CreatorRecruitmentFunnel {
  /** Primary key (UUID). */
  id: string;
  /** UUID of the creator (FK → creators.id). Unique per row. */
  creator_id: string;
  /** Recruitment tier (1, 2, or 3). */
  tier: CreatorTier;
  /** Current lifecycle state. */
  status: CreatorRecruitmentStatus;
  /** How this creator was sourced. */
  recruitment_source: CreatorRecruitmentSource;
  /** ISO timestamp when the creator signed; `null` for unsigned prospects. */
  signed_date: string | null;
  /** Rolling performance score (0..100). Tier upgrades at 50 (T1→T2) and 75 (T2→T3). */
  performance_score: number;
  /** ISO timestamp when the row was inserted. */
  created_at: string;
  /** ISO timestamp of the last update. */
  updated_at: string;
}

// ---------------------------------------------------------------------------
// 005_claim_appeals
// ---------------------------------------------------------------------------

/** Appeal lifecycle state. */
export type ClaimAppealStatus =
  | "submitted"
  | "under_review"
  | "approved"
  | "rejected";

/**
 * Creator appeal against a rejected verified-customer claim. Submitted by the
 * creator, reviewed by the merchant. Approved appeals roll back into
 * ai_accuracy_audits as false_negatives, which retunes verification
 * thresholds.
 */
export interface ClaimAppeal {
  /** Primary key (UUID). */
  id: string;
  /** UUID of the appealing creator (FK → creators.id). */
  creator_id: string;
  /** UUID of the merchant who originally rejected the claim (FK → merchants.id). */
  merchant_id: string;
  /** UUID of the disputed claim (FK → verified_customer_claims.id, added later). */
  claim_id: string;
  /** Creator's free-form explanation of why the claim should be approved. */
  appeal_reason: string;
  /** Optional URL to supporting evidence (photo, receipt, etc.). */
  supporting_evidence_url: string | null;
  /** Current appeal state. */
  status: ClaimAppealStatus;
  /** Merchant's free-form decision rationale; populated when reviewed. */
  merchant_decision: string | null;
  /** UUID of the merchant-side reviewer who took the decision. */
  merchant_id_reviewer: string | null;
  /** ISO timestamp when the appeal was reviewed; `null` until then. */
  reviewed_at: string | null;
  /** ISO timestamp when the row was inserted. */
  created_at: string;
  /** ISO timestamp of the last update. */
  updated_at: string;
}

// ---------------------------------------------------------------------------
// 006_neighborhood_profiles
// ---------------------------------------------------------------------------

/** Neighborhood rollout state. */
export type NeighborhoodStatus = "planning" | "pilot" | "active" | "mature";

/**
 * Per-neighborhood pilot management: targets, current state, pricing tier,
 * seasonality. One row per neighborhood (e.g. "Williamsburg Coffee+").
 * Drives Neighborhood Playbook rollout and the SLR (Software Leverage Ratio)
 * calculation.
 */
export interface NeighborhoodProfile {
  /** Primary key (UUID). */
  id: string;
  /** Human-readable identifier, e.g. "Williamsburg Coffee+". Unique per row. */
  neighborhood_name: string;
  /** Latitude of the neighborhood centroid (-90..90), or `null`. */
  latitude: number | null;
  /** Longitude of the neighborhood centroid (-180..180), or `null`. */
  longitude: number | null;
  /** Target merchant count at maturity. */
  merchants_target: number;
  /** Current onboarded merchant count. */
  merchants_current: number;
  /** Target monthly ARR in USD. */
  monthly_target_arr: number;
  /** Current monthly ARR in USD. */
  monthly_current_arr: number;
  /** Pricing tier label (maps to v5.1 $15-$85/customer band). */
  pricing_tier: string | null;
  /** Forecast multiplier (0..5); 1.0 = flat, >1 = peak season. */
  seasonality_factor: number;
  /** Rollout state. */
  status: NeighborhoodStatus;
  /** ISO timestamp when the row was inserted. */
  created_at: string;
  /** ISO timestamp of the last update. */
  updated_at: string;
}
