// Mock QR code data layer for demo/attribution system
// Each QR code represents a unique creator-campaign-merchant binding
// In production: replace with Supabase query

export type QRScanEntry = {
  userId: string; // anonymous browser-generated ID
  scannedAt: string; // ISO timestamp
  userAgent: string;
  referrer: string;
};

export type MockQRCode = {
  qrId: string;
  campaignId: string;
  creatorId: string;
  merchantId: string;
  creatorName: string;
  creatorHandle: string;
  campaignTitle: string;
  businessName: string;
  businessAddress: string;
  category: string;
  description: string;
  offerTier1: string; // Hero offer (limited slots)
  offerTier2: string; // Sustained offer (always available)
  heroSlotsTotal: number;
  heroSlotsUsed: number;
  payout: number;
  lat: number;
  lng: number;
  issuedAt: string;
  expiresAt: string;
  scannedBy: QRScanEntry[];
};

// 20 mock QR codes tied to DEMO_CAMPAIGNS in creator dashboard
export const MOCK_QR_CODES: MockQRCode[] = [
  {
    qrId: "qr-bsc-001",
    campaignId: "camp-001",
    creatorId: "demo-creator-001",
    merchantId: "merchant-blank-street",
    creatorName: "Alex Chen",
    creatorHandle: "alexcheneats",
    campaignTitle: "Morning Ritual Campaign",
    businessName: "Blank Street Coffee",
    businessAddress: "5 W 19th St, New York, NY 10011",
    category: "Coffee",
    description:
      "Visit any Blank Street location, enjoy a drink, and share your experience. Perfect for building your portfolio.",
    offerTier1: "Free matcha latte (first 10 customers)",
    offerTier2: "15% off any drink",
    heroSlotsTotal: 10,
    heroSlotsUsed: 3,
    payout: 0,
    lat: 40.7395,
    lng: -73.994,
    issuedAt: "2026-04-01T00:00:00Z",
    expiresAt: "2026-04-30T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-sup-002",
    campaignId: "camp-002",
    creatorId: "demo-creator-001",
    merchantId: "merchant-superiority",
    creatorName: "Alex Chen",
    creatorHandle: "alexcheneats",
    campaignTitle: "Best Burger in NYC Feature",
    businessName: "Superiority Burger",
    businessAddress: "119 Avenue A, New York, NY 10009",
    category: "Food",
    description:
      "Feature our award-winning veggie burgers in an authentic review.",
    offerTier1: "Free Classic Burger (first 5 customers)",
    offerTier2: "$2 off any burger",
    heroSlotsTotal: 5,
    heroSlotsUsed: 5,
    payout: 35,
    lat: 40.726,
    lng: -73.9831,
    issuedAt: "2026-04-01T00:00:00Z",
    expiresAt: "2026-04-25T23:59:59Z",
    scannedBy: [
      {
        userId: "anon-aaa111",
        scannedAt: "2026-04-10T14:22:00Z",
        userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0)",
        referrer: "https://instagram.com",
      },
      {
        userId: "anon-bbb222",
        scannedAt: "2026-04-11T12:05:00Z",
        userAgent: "Mozilla/5.0 (Android 14)",
        referrer: "https://instagram.com/stories",
      },
    ],
  },
  {
    qrId: "qr-fla-003",
    campaignId: "camp-003",
    creatorId: "demo-creator-001",
    merchantId: "merchant-flamingo",
    creatorName: "Alex Chen",
    creatorHandle: "alexcheneats",
    campaignTitle: "LA Botanica Aesthetic Shoot",
    businessName: "Flamingo Estate",
    businessAddress: "La Guardia Pl, New York, NY 10012",
    category: "Lifestyle",
    description:
      "Capture the Flamingo Estate aesthetic at our NYC pop-up. Moody, editorial, nature-forward content.",
    offerTier1: "Complimentary tote + 20% off purchase",
    offerTier2: "10% off sitewide",
    heroSlotsTotal: 8,
    heroSlotsUsed: 2,
    payout: 75,
    lat: 40.7291,
    lng: -74.0018,
    issuedAt: "2026-04-05T00:00:00Z",
    expiresAt: "2026-05-05T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-bth-004",
    campaignId: "camp-004",
    creatorId: "demo-creator-002",
    merchantId: "merchant-brow-theory",
    creatorName: "Maya Kim",
    creatorHandle: "mayakimnyc",
    campaignTitle: "Brow Transformation Story",
    businessName: "Brow Theory",
    businessAddress: "247 Centre St, New York, NY 10013",
    category: "Beauty",
    description:
      "Document your brow transformation at Brow Theory. Before/after content preferred.",
    offerTier1: "Free brow consultation + 30% off first service",
    offerTier2: "15% off all services",
    heroSlotsTotal: 10,
    heroSlotsUsed: 4,
    payout: 50,
    lat: 40.7195,
    lng: -74.0018,
    issuedAt: "2026-04-03T00:00:00Z",
    expiresAt: "2026-04-28T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-glo-005",
    campaignId: "camp-005",
    creatorId: "demo-creator-003",
    merchantId: "merchant-glossier",
    creatorName: "Priya Nair",
    creatorHandle: "priyanairbeauty",
    campaignTitle: "Glossier NYC Store Experience",
    businessName: "Glossier",
    businessAddress: "1a York Ave, New York, NY 10065",
    category: "Beauty",
    description:
      "Create editorial beauty content at the Glossier flagship. High production value expected.",
    offerTier1: "Free Balm Dotcom + 25% off purchase",
    offerTier2: "15% off sitewide",
    heroSlotsTotal: 15,
    heroSlotsUsed: 8,
    payout: 120,
    lat: 40.7625,
    lng: -73.9577,
    issuedAt: "2026-04-05T00:00:00Z",
    expiresAt: "2026-05-10T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-lbf-006",
    campaignId: "camp-006",
    creatorId: "demo-creator-004",
    merchantId: "merchant-le-bec-fin",
    creatorName: "Jordan Rivers",
    creatorHandle: "jordanrivers",
    campaignTitle: "Le Bec-Fin Pop-Up Review",
    businessName: "Le Bec Fin",
    businessAddress: "1 Rockefeller Plaza, New York, NY 10020",
    category: "Food",
    description:
      "Try the NYC pop-up of the legendary Philadelphia institution. Share an honest review.",
    offerTier1: "Complimentary amuse-bouche for two",
    offerTier2: "$5 off any entree",
    heroSlotsTotal: 5,
    heroSlotsUsed: 5,
    payout: 20,
    lat: 40.7597,
    lng: -73.9787,
    issuedAt: "2026-04-01T00:00:00Z",
    expiresAt: "2026-04-22T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-kth-007",
    campaignId: "camp-007",
    creatorId: "demo-creator-005",
    merchantId: "merchant-kith",
    creatorName: "Sam Torres",
    creatorHandle: "samtorresnyc",
    campaignTitle: "KITH x Creator Collab Series",
    businessName: "KITH",
    businessAddress: "337 Lafayette St, New York, NY 10012",
    category: "Retail",
    description:
      "Exclusive creator collab at KITH SoHo. Style editorial campaign for Spring 2026 collection.",
    offerTier1: "Exclusive early access + styling session",
    offerTier2: "20% off Spring 2026 collection",
    heroSlotsTotal: 3,
    heroSlotsUsed: 1,
    payout: 199,
    lat: 40.7248,
    lng: -74.0012,
    issuedAt: "2026-04-10T00:00:00Z",
    expiresAt: "2026-05-15T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-ccm-008",
    campaignId: "camp-008",
    creatorId: "demo-creator-001",
    merchantId: "merchant-cha-cha-matcha",
    creatorName: "Alex Chen",
    creatorHandle: "alexcheneats",
    campaignTitle: "Matcha Morning Ritual",
    businessName: "Cha Cha Matcha",
    businessAddress: "373 Broadway, New York, NY 10013",
    category: "Coffee",
    description:
      "Share your morning matcha ritual at Cha Cha Matcha. Aesthetic, cozy content welcome.",
    offerTier1: "Free matcha latte (first 8 customers)",
    offerTier2: "BOGO 50% off matcha",
    heroSlotsTotal: 8,
    heroSlotsUsed: 3,
    payout: 25,
    lat: 40.7178,
    lng: -74.003,
    issuedAt: "2026-04-05T00:00:00Z",
    expiresAt: "2026-04-29T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-rdm-009",
    campaignId: "camp-009",
    creatorId: "demo-creator-002",
    merchantId: "merchant-ramen-danbo",
    creatorName: "Maya Kim",
    creatorHandle: "mayakimnyc",
    campaignTitle: "Ramen Danbo NYC Launch",
    businessName: "Ramen Danbo",
    businessAddress: "43 W 55th St, New York, NY 10019",
    category: "Food",
    description:
      "Be among the first to feature Ramen Danbo's NYC outpost. Authentic tonkotsu, curated experience.",
    offerTier1: "Free kaedama (noodle refill) + priority seating",
    offerTier2: "$3 off any ramen bowl",
    heroSlotsTotal: 12,
    heroSlotsUsed: 7,
    payout: 45,
    lat: 40.762,
    lng: -73.979,
    issuedAt: "2026-04-08T00:00:00Z",
    expiresAt: "2026-05-08T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-fby-010",
    campaignId: "camp-010",
    creatorId: "demo-creator-003",
    merchantId: "merchant-fig-by-fig",
    creatorName: "Priya Nair",
    creatorHandle: "priyanairbeauty",
    campaignTitle: "Fig & Flower Brunch Series",
    businessName: "Fig by Fig",
    businessAddress: "183 Lorimer St, Brooklyn, NY 11206",
    category: "Food",
    description:
      "Feature Fig by Fig's editorial brunch menu in Williamsburg. Botanical, refined, shareable.",
    offerTier1: "Complimentary bottomless mimosas for two",
    offerTier2: "15% off food items",
    heroSlotsTotal: 10,
    heroSlotsUsed: 4,
    payout: 60,
    lat: 40.718,
    lng: -73.9497,
    issuedAt: "2026-04-07T00:00:00Z",
    expiresAt: "2026-05-07T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-lmn-011",
    campaignId: "camp-011",
    creatorId: "demo-creator-004",
    merchantId: "merchant-lemon-grove",
    creatorName: "Jordan Rivers",
    creatorHandle: "jordanrivers",
    campaignTitle: "Lemon Grove Wellness Pop-Up",
    businessName: "Lemon Grove",
    businessAddress: "280 Mott St, New York, NY 10012",
    category: "Lifestyle",
    description:
      "Capture the wellness vibes at Lemon Grove's Nolita pop-up. Clean aesthetic, bright light.",
    offerTier1: "Free wellness shot flight",
    offerTier2: "10% off all cold-press juices",
    heroSlotsTotal: 8,
    heroSlotsUsed: 2,
    payout: 40,
    lat: 40.7227,
    lng: -73.9955,
    issuedAt: "2026-04-09T00:00:00Z",
    expiresAt: "2026-04-30T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-slt-012",
    campaignId: "camp-012",
    creatorId: "demo-creator-005",
    merchantId: "merchant-salt-n-straw",
    creatorName: "Sam Torres",
    creatorHandle: "samtorresnyc",
    campaignTitle: "Salt & Straw NYC Debut",
    businessName: "Salt & Straw",
    businessAddress: "87 Prince St, New York, NY 10012",
    category: "Food",
    description:
      "First NYC location launch. Feature the rotating seasonal menu — artisan, Portland-original.",
    offerTier1: "Free single scoop + tasting flight",
    offerTier2: "$2 off any scoop",
    heroSlotsTotal: 20,
    heroSlotsUsed: 11,
    payout: 30,
    lat: 40.7253,
    lng: -73.9963,
    issuedAt: "2026-04-10T00:00:00Z",
    expiresAt: "2026-05-10T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-vel-013",
    campaignId: "camp-013",
    creatorId: "demo-creator-001",
    merchantId: "merchant-velvet-brooklyn",
    creatorName: "Alex Chen",
    creatorHandle: "alexcheneats",
    campaignTitle: "Velvet Brooklyn Cocktail Series",
    businessName: "Velvet Brooklyn",
    businessAddress: "419 Graham Ave, Brooklyn, NY 11211",
    category: "Lifestyle",
    description:
      "Craft cocktail bar meets editorial aesthetic. Evening shoot — moody, intimate, refined.",
    offerTier1: "Complimentary welcome cocktail",
    offerTier2: "Happy hour pricing all night",
    heroSlotsTotal: 6,
    heroSlotsUsed: 1,
    payout: 55,
    lat: 40.7132,
    lng: -73.9415,
    issuedAt: "2026-04-11T00:00:00Z",
    expiresAt: "2026-05-11T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-ths-014",
    campaignId: "camp-014",
    creatorId: "demo-creator-002",
    merchantId: "merchant-the-smile",
    creatorName: "Maya Kim",
    creatorHandle: "mayakimnyc",
    campaignTitle: "The Smile Brunch Feature",
    businessName: "The Smile",
    businessAddress: "26 Bond St, New York, NY 10012",
    category: "Food",
    description:
      "Nolita institution, day-to-night vibe. Feature the weekend brunch menu.",
    offerTier1: "Complimentary avocado toast + coffee",
    offerTier2: "10% off all brunch items",
    heroSlotsTotal: 8,
    heroSlotsUsed: 6,
    payout: 35,
    lat: 40.7263,
    lng: -73.9927,
    issuedAt: "2026-04-06T00:00:00Z",
    expiresAt: "2026-04-27T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-pvb-015",
    campaignId: "camp-015",
    creatorId: "demo-creator-003",
    merchantId: "merchant-pavement-books",
    creatorName: "Priya Nair",
    creatorHandle: "priyanairbeauty",
    campaignTitle: "Pavement Books x Creator",
    businessName: "Pavement Books",
    businessAddress: "36 Perry St, New York, NY 10014",
    category: "Retail",
    description:
      "West Village independent bookshop. Cozy, curated — share your reading aesthetic.",
    offerTier1: "Free book selection (up to $20 value)",
    offerTier2: "15% off any purchase",
    heroSlotsTotal: 5,
    heroSlotsUsed: 2,
    payout: 40,
    lat: 40.7348,
    lng: -74.0037,
    issuedAt: "2026-04-08T00:00:00Z",
    expiresAt: "2026-05-08T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-ftn-016",
    campaignId: "camp-016",
    creatorId: "demo-creator-004",
    merchantId: "merchant-fountain-beauty",
    creatorName: "Jordan Rivers",
    creatorHandle: "jordanrivers",
    campaignTitle: "Fountain Beauty Launch",
    businessName: "Fountain Beauty",
    businessAddress: "158 Spring St, New York, NY 10012",
    category: "Beauty",
    description:
      "Minimalist skincare brand launch in SoHo. Clean, clinical, aspirational editorial.",
    offerTier1: "Free signature facial + starter kit",
    offerTier2: "20% off first purchase",
    heroSlotsTotal: 10,
    heroSlotsUsed: 5,
    payout: 90,
    lat: 40.7244,
    lng: -74.0013,
    issuedAt: "2026-04-09T00:00:00Z",
    expiresAt: "2026-05-09T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-rpm-017",
    campaignId: "camp-017",
    creatorId: "demo-creator-005",
    merchantId: "merchant-rpm-fitness",
    creatorName: "Sam Torres",
    creatorHandle: "samtorresnyc",
    campaignTitle: "RPM Fitness Open Week",
    businessName: "RPM Fitness",
    businessAddress: "11 E 44th St, New York, NY 10017",
    category: "Fitness",
    description:
      "Premium cycling studio launch week. Capture the energy, the community, the sweat.",
    offerTier1: "Free class + RPM branded water bottle",
    offerTier2: "30% off first month membership",
    heroSlotsTotal: 15,
    heroSlotsUsed: 9,
    payout: 65,
    lat: 40.7527,
    lng: -73.9772,
    issuedAt: "2026-04-12T00:00:00Z",
    expiresAt: "2026-05-12T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-tbn-018",
    campaignId: "camp-018",
    creatorId: "demo-creator-001",
    merchantId: "merchant-the-butcher",
    creatorName: "Alex Chen",
    creatorHandle: "alexcheneats",
    campaignTitle: "The Butcher's Daughter Relaunch",
    businessName: "The Butcher's Daughter",
    businessAddress: "19 Kenmare St, New York, NY 10012",
    category: "Food",
    description:
      "Plant-based Nolita icon relaunches spring menu. Feature the new seasonal dishes.",
    offerTier1: "Complimentary seasonal tasting plate",
    offerTier2: "$5 off entrees over $20",
    heroSlotsTotal: 8,
    heroSlotsUsed: 3,
    payout: 50,
    lat: 40.7218,
    lng: -73.9957,
    issuedAt: "2026-04-10T00:00:00Z",
    expiresAt: "2026-05-10T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-spl-019",
    campaignId: "camp-019",
    creatorId: "demo-creator-002",
    merchantId: "merchant-split",
    creatorName: "Maya Kim",
    creatorHandle: "mayakimnyc",
    campaignTitle: "Split Wine Bar Evening",
    businessName: "Split",
    businessAddress: "230 9th Ave, New York, NY 10001",
    category: "Lifestyle",
    description:
      "Chelsea wine bar with natural wine focus. Intimate evening editorial shoot.",
    offerTier1: "Complimentary glass of natural wine",
    offerTier2: "10% off bottles",
    heroSlotsTotal: 6,
    heroSlotsUsed: 0,
    payout: 45,
    lat: 40.7461,
    lng: -74.0003,
    issuedAt: "2026-04-13T00:00:00Z",
    expiresAt: "2026-05-13T23:59:59Z",
    scannedBy: [],
  },
  {
    qrId: "qr-prx-020",
    campaignId: "camp-020",
    creatorId: "demo-creator-003",
    merchantId: "merchant-procell",
    creatorName: "Priya Nair",
    creatorHandle: "priyanairbeauty",
    campaignTitle: "Procell Hair Treatment Feature",
    businessName: "Procell Therapies",
    businessAddress: "30 E 60th St, New York, NY 10022",
    category: "Beauty",
    description:
      "Next-gen hair restoration treatment. Before/after documentary content. Science-meets-luxury.",
    offerTier1: "Complimentary microchanneling session",
    offerTier2: "25% off first treatment",
    heroSlotsTotal: 5,
    heroSlotsUsed: 1,
    payout: 150,
    lat: 40.7634,
    lng: -73.9693,
    issuedAt: "2026-04-11T00:00:00Z",
    expiresAt: "2026-05-11T23:59:59Z",
    scannedBy: [],
  },
];

// Helper: look up a QR code by ID
export function getQRCode(qrId: string): MockQRCode | undefined {
  return MOCK_QR_CODES.find((q) => q.qrId === qrId);
}

// Helper: is the QR code still within its validity window?
export function isQRExpired(qr: MockQRCode): boolean {
  return new Date() > new Date(qr.expiresAt);
}

// Helper: hero slots remaining
export function heroSlotsRemaining(qr: MockQRCode): number {
  return Math.max(0, qr.heroSlotsTotal - qr.heroSlotsUsed);
}
