import type { Analytics, Application, Campaign, Merchant } from './types';

export const DEMO_MERCHANT: Merchant = {
  id: 'demo-merchant-001',
  user_id: 'demo-merchant-user-001',
  business_name: 'Blank Street Coffee — SoHo',
  address: '284 W Broadway, New York, NY 10013',
  contact_email: 'ops@blankstreetcoffee.com',
  instagram: '@blankstreetcoffee',
  plan: 'growth',
};

export const DEMO_CAMPAIGNS: Campaign[] = [
  {
    id: 'demo-campaign-001',
    title: 'Free Latte for a 30-Second Reel',
    description:
      'Come in, order any latte, and capture a 30-second Reel showing your experience — from ordering to that first sip.',
    category: 'Food & Drink',
    payout: 0,
    spots_total: 12,
    spots_remaining: 8,
    deadline: '2026-04-20T23:59:00Z',
    created_at: '2026-04-01T10:00:00Z',
    status: 'active',
    applications_count: 4,
    qr_scans: 28,
    attributed_revenue: 420,
  },
  {
    id: 'demo-campaign-mc-002',
    title: 'Morning Rush Special Reel',
    description:
      'Capture the 7:30–9am morning rush at Blank Street — the queue, the baristas, the regulars.',
    category: 'Food & Drink',
    payout: 65,
    spots_total: 5,
    spots_remaining: 3,
    deadline: '2026-04-26T23:59:00Z',
    created_at: '2026-04-05T08:00:00Z',
    status: 'active',
    applications_count: 2,
    qr_scans: 19,
    attributed_revenue: 820,
  },
  {
    id: 'demo-campaign-mc-003',
    title: 'Holiday Blend Launch',
    description:
      'Cover our seasonal holiday blend launch — the ritual, the packaging, the first pour.',
    category: 'Food & Drink',
    payout: 30,
    spots_total: 8,
    spots_remaining: 0,
    deadline: '2026-03-15T23:59:00Z',
    created_at: '2026-02-28T10:00:00Z',
    status: 'closed',
    applications_count: 4,
    qr_scans: 0,
    attributed_revenue: 640,
  },
];

export const DEMO_APPLICATIONS: Application[] = [
  {
    id: 'demo-app-m-001',
    campaign_id: 'demo-campaign-001',
    campaign_title: 'Free Latte for a 30-Second Reel',
    creator_name: 'Sofia Martinez',
    creator_handle: '@sofiainyc',
    creator_tier: 'explorer',
    creator_score: 47,
    creator_avatar:
      'https://api.dicebear.com/7.x/avataaars/svg?seed=SofiaMartinez',
    creator_followers: 3100,
    status: 'accepted',
    milestone: 'proof_submitted',
    proof_url: 'https://www.instagram.com/reel/demo-proof-1',
    applied_at: '2026-04-08T10:20:00Z',
  },
  {
    id: 'demo-app-m-002',
    campaign_id: 'demo-campaign-001',
    campaign_title: 'Free Latte for a 30-Second Reel',
    creator_name: 'James Liu',
    creator_handle: '@jamesliu.eats',
    creator_tier: 'operator',
    creator_score: 68,
    creator_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=JamesLiu',
    creator_followers: 5800,
    status: 'accepted',
    milestone: 'settled',
    content_url: 'https://www.instagram.com/reel/demo-content-2',
    applied_at: '2026-04-06T14:10:00Z',
    merchant_rating: 5,
  },
  {
    id: 'demo-app-m-003',
    campaign_id: 'demo-campaign-001',
    campaign_title: 'Free Latte for a 30-Second Reel',
    creator_name: 'Alex Chen',
    creator_handle: '@alexchen.nyc',
    creator_tier: 'operator',
    creator_score: 71,
    creator_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlexChen',
    creator_followers: 4200,
    status: 'accepted',
    milestone: 'accepted',
    applied_at: '2026-04-10T09:15:00Z',
  },
  {
    id: 'demo-app-m-004',
    campaign_id: 'demo-campaign-001',
    campaign_title: 'Free Latte for a 30-Second Reel',
    creator_name: 'Tom Park',
    creator_handle: '@tompark.nyc',
    creator_tier: 'explorer',
    creator_score: 52,
    creator_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TomPark',
    creator_followers: 2400,
    status: 'pending',
    milestone: 'accepted',
    applied_at: '2026-04-11T16:45:00Z',
  },
  {
    id: 'demo-app-m-005',
    campaign_id: 'demo-campaign-mc-002',
    campaign_title: 'Morning Rush Special Reel',
    creator_name: 'Rachel Kim',
    creator_handle: '@rachelkimnyc',
    creator_tier: 'proven',
    creator_score: 79,
    creator_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RachelKim',
    creator_followers: 12400,
    status: 'accepted',
    milestone: 'content_published',
    content_url: 'https://www.instagram.com/reel/demo-content-5',
    applied_at: '2026-04-07T08:30:00Z',
  },
  {
    id: 'demo-app-m-006',
    campaign_id: 'demo-campaign-mc-002',
    campaign_title: 'Morning Rush Special Reel',
    creator_name: 'Maya Johnson',
    creator_handle: '@mayaj.creates',
    creator_tier: 'seed',
    creator_score: 31,
    creator_avatar:
      'https://api.dicebear.com/7.x/avataaars/svg?seed=MayaJohnson',
    creator_followers: 890,
    status: 'pending',
    milestone: 'accepted',
    applied_at: '2026-04-11T11:00:00Z',
  },
];

export const DEMO_ANALYTICS: Analytics = {
  qr_scans_month: 47,
  qr_scans_delta: 12,
  new_customers: 34,
  active_creators: 5,
  total_spend: 315,
  estimated_revenue: 1240,
  roi_multiple: 3.9,
};
