// v11 About Page — Marketing editorial register
// No about.css import — all layout via global tokens + inline styles

import Link from "next/link";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

/* ── Team data ─────────────────────────────────────────────── */
const TEAM = [
  {
    initial: "J",
    name: "Jiaming Wang",
    role: "FOUNDER · CEO",
    origin: "Mott Street native · Built Push from a restaurant booth",
  },
  {
    initial: "?",
    name: "—",
    role: "ENGINEERING · ATTRIBUTION",
    origin: "QR → scan → payout rail · Previously Square",
  },
  {
    initial: "?",
    name: "—",
    role: "OPERATIONS · CREATOR SIDE",
    origin: "Reads every application · Walks Tribeca on weekends",
  },
  {
    initial: "?",
    name: "—",
    role: "DESIGN · BRAND SURFACE",
    origin: "Sets the type, the color, the weight",
  },
  {
    initial: "?",
    name: "—",
    role: "GROWTH · MERCHANT SIDE",
    origin: "Cold-opens new neighborhoods · Brooklyn-born",
  },
];

/* ── Values data ──────────────────────────────────────────── */
const VALUES = [
  {
    title: "Verified scans only",
    body: "Every verified visit is confirmed by QR scan, device GPS dwell, and timestamp alignment. If all three don't match, it doesn't count. No impressions, no reach, no estimates — only physical presence.",
    icon: (
      <svg
        width="22"
        height="22"
        viewBox="0 0 24 24"
        fill="none"
        stroke="white"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
        <polyline points="9 12 11 14 15 10" />
      </svg>
    ),
  },
  {
    title: "Real creators, real blocks",
    body: "We launched in Brooklyn because hyper-local trust is built block by block. Our creator network lives in the neighborhoods they promote. We expand only when we can verify that same ground-level density in the next market.",
    icon: (
      <svg
        width="22"
        height="22"
        viewBox="0 0 24 24"
        fill="none"
        stroke="white"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z" />
        <circle cx="12" cy="10" r="3" />
      </svg>
    ),
  },
  {
    title: "Physical presence counts",
    body: "Push is incorporated as a Public Benefit Corporation. Creator payouts are structured so that the value generated by foot traffic flows back to the people who walked those blocks — not to an ad intermediary's margin.",
    icon: (
      <svg
        width="22"
        height="22"
        viewBox="0 0 24 24"
        fill="none"
        stroke="white"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <line x1="5" y1="12" x2="19" y2="12" />
        <line x1="5" y1="8" x2="19" y2="8" />
        <line x1="5" y1="16" x2="19" y2="16" />
      </svg>
    ),
  },
];

export default function AboutPage() {
  return (
    <>
      <Header />

      <main>
        {/* ═══════════════════════════════════════════════════════
            HERO Panel — full-bleed dark gradient, bottom-left title
            ═══════════════════════════════════════════════════════ */}
        <section
          style={{
            position: "relative",
            width: "100%",
            height: "clamp(480px, 70vh, 720px)",
            borderRadius: 0,
            overflow: "hidden",
            background: `
              linear-gradient(180deg, rgba(0,0,0,0.10) 0%, rgba(0,0,0,0.65) 100%),
              radial-gradient(ellipse 100% 80% at 65% 25%, rgba(30,95,173,0.22) 0%, transparent 55%),
              radial-gradient(ellipse 70% 90% at 15% 85%, rgba(193,18,31,0.12) 0%, transparent 50%),
              linear-gradient(170deg, #1e1c19 0%, #2c2a26 100%)
            `,
          }}
        >
          {/* Bottom-left content anchor */}
          <div
            style={{
              position: "absolute",
              bottom: 96,
              left: 64,
              maxWidth: 720,
              zIndex: 2,
            }}
          >
            <p
              className="eyebrow"
              style={{
                color: "rgba(255,255,255,0.75)",
                marginBottom: 16,
              }}
            >
              (OUR STORY)
            </p>

            <h1
              style={{
                fontFamily: "var(--font-hero)",
                fontStyle: "normal",
                fontWeight: 400,
                fontSize: "clamp(64px, 9vw, 160px)",
                letterSpacing: "-0.022em",
                lineHeight: 0.88,
                color: "var(--snow)",
                margin: 0,
              }}
            >
              Built in
              <br />
              Brooklyn.
            </h1>

            <p
              style={{
                fontFamily: "var(--font-body)",
                fontSize: 18,
                color: "rgba(255,255,255,0.70)",
                lineHeight: 1.6,
                maxWidth: "48ch",
                marginTop: 32,
                marginBottom: 0,
              }}
            >
              Push started in Williamsburg because that&rsquo;s where we live,
              eat, and know by name.
            </p>

            <div style={{ marginTop: 48 }}>
              <Link href="/creator/signup" className="btn-primary click-shift">
                Join Push
              </Link>
            </div>
          </div>
        </section>

        {/* ═══════════════════════════════════════════════════════
            STORY Panel — Candy Butter + floating stat tiles
            ═══════════════════════════════════════════════════════ */}
        <section
          className="candy-panel"
          style={{
            background: "var(--panel-butter)",
            position: "relative",
          }}
        >
          {/* Top-left heading block */}
          <p
            className="eyebrow"
            style={{
              color: "var(--ink-3)",
              marginBottom: 16,
            }}
          >
            (WHY THIS EXISTS)
          </p>

          <h2
            style={{
              fontFamily: "var(--font-display)",
              fontWeight: 800,
              fontSize: 40,
              letterSpacing: "-0.04em",
              lineHeight: 1.1,
              color: "var(--ink)",
              margin: "0 0 32px",
              maxWidth: "20ch",
            }}
          >
            Performance marketing
            <br />
            that lives on the street.
          </h2>

          <p
            style={{
              fontFamily: "var(--font-body)",
              fontSize: 18,
              color: "var(--ink-3)",
              lineHeight: 1.55,
              maxWidth: "60ch",
              marginBottom: 32,
            }}
          >
            We built Push because digital ads stopped working for local
            businesses. Impressions don&rsquo;t mean foot traffic. Reach
            doesn&rsquo;t mean revenue. We measure exactly one thing: verified
            physical visits.
          </p>

          <p
            style={{
              fontFamily: "var(--font-body)",
              fontSize: 18,
              color: "var(--ink-3)",
              lineHeight: 1.55,
              maxWidth: "60ch",
              marginBottom: 48,
            }}
          >
            Every scan is confirmed by QR scan + GPS dwell + timestamp. If all
            three don&rsquo;t match, it doesn&rsquo;t count. That&rsquo;s the
            standard we hold ourselves to.
          </p>

          {/* Floating stat tiles — 3 columns */}
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(3, 1fr)",
              gap: 24,
            }}
          >
            {[
              { num: "1.4M+", label: "Verified visits" },
              { num: "100+", label: "NYC merchants" },
              { num: "87%", label: "Creator retention" },
            ].map((stat) => (
              <div
                key={stat.label}
                className="lg-surface"
                style={{
                  borderRadius: 16,
                  padding: 32,
                }}
              >
                <p
                  style={{
                    fontFamily: "var(--font-display)",
                    fontWeight: 800,
                    fontSize: "clamp(32px, 4vw, 48px)",
                    letterSpacing: "-0.04em",
                    lineHeight: 1,
                    color: "var(--ink)",
                    margin: "0 0 8px",
                  }}
                >
                  {stat.num}
                </p>
                <p
                  className="eyebrow"
                  style={{
                    color: "var(--ink-3)",
                    margin: 0,
                  }}
                >
                  {stat.label}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* ═══════════════════════════════════════════════════════
            Sig Divider
            ═══════════════════════════════════════════════════════ */}
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            padding: "0 64px",
          }}
        >
          <span className="sig-divider">Real · Local · Verified ·</span>
        </div>

        {/* ═══════════════════════════════════════════════════════
            VALUES Panel — Candy Sky
            ═══════════════════════════════════════════════════════ */}
        <section
          className="candy-panel"
          style={{
            background: "var(--panel-sky)",
          }}
        >
          <p
            className="eyebrow"
            style={{
              color: "var(--ink-3)",
              marginBottom: 16,
            }}
          >
            (WHAT WE BELIEVE)
          </p>

          <h2
            style={{
              fontFamily: "var(--font-display)",
              fontWeight: 800,
              fontSize: 40,
              letterSpacing: "-0.04em",
              lineHeight: 1.1,
              color: "var(--ink)",
              margin: "0 0 48px",
            }}
          >
            Three rules
            <br />
            we don&rsquo;t break.
          </h2>

          {/* Value cards */}
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(3, 1fr)",
              gap: 24,
            }}
          >
            {VALUES.map((v) => (
              <div
                key={v.title}
                className="click-shift"
                style={{
                  background: "rgba(255,255,255,0.55)",
                  borderRadius: 16,
                  padding: 24,
                }}
              >
                {/* Icon tile */}
                <div
                  style={{
                    width: 40,
                    height: 40,
                    borderRadius: 12,
                    background: "var(--ink)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    marginBottom: 16,
                    flexShrink: 0,
                  }}
                >
                  {v.icon}
                </div>

                <h3
                  style={{
                    fontFamily: "var(--font-display)",
                    fontWeight: 700,
                    fontSize: 20,
                    letterSpacing: "-0.02em",
                    lineHeight: 1.2,
                    color: "var(--ink)",
                    margin: "0 0 12px",
                  }}
                >
                  {v.title}
                </h3>

                <p
                  style={{
                    fontFamily: "var(--font-body)",
                    fontSize: 16,
                    color: "var(--ink-3)",
                    lineHeight: 1.6,
                    margin: 0,
                  }}
                >
                  {v.body}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* ═══════════════════════════════════════════════════════
            TEAM Panel — Surface-2 Pearl Stone
            ═══════════════════════════════════════════════════════ */}
        <section
          style={{
            background: "var(--surface-2)",
            padding: "96px 64px",
          }}
        >
          <div style={{ maxWidth: "var(--content-width)", margin: "0 auto" }}>
            <p
              className="eyebrow"
              style={{
                color: "var(--ink-3)",
                marginBottom: 16,
              }}
            >
              (THE TEAM)
            </p>

            <h2
              style={{
                fontFamily: "var(--font-display)",
                fontWeight: 800,
                fontSize: 40,
                letterSpacing: "-0.04em",
                lineHeight: 1.1,
                color: "var(--ink)",
                margin: "0 0 48px",
              }}
            >
              The people
              <br />
              behind the scans.
            </h2>

            {/* 5-col desktop team grid */}
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(5, 1fr)",
                gap: 24,
              }}
            >
              {TEAM.map((member) => (
                <div
                  key={member.name + member.role}
                  style={{ display: "flex", flexDirection: "column", gap: 8 }}
                >
                  {/* Avatar circle */}
                  <div
                    style={{
                      width: 40,
                      height: 40,
                      borderRadius: "50%",
                      background: "var(--ink)",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      marginBottom: 8,
                      flexShrink: 0,
                    }}
                  >
                    <span
                      style={{
                        fontFamily: "var(--font-display)",
                        fontWeight: 700,
                        fontSize: 16,
                        color: "var(--snow)",
                        lineHeight: 1,
                      }}
                    >
                      {member.initial}
                    </span>
                  </div>

                  <p
                    style={{
                      fontFamily: "var(--font-display)",
                      fontWeight: 700,
                      fontSize: 18,
                      letterSpacing: "-0.02em",
                      color: "var(--ink)",
                      margin: 0,
                      lineHeight: 1.2,
                    }}
                  >
                    {member.name}
                  </p>

                  <p
                    className="eyebrow"
                    style={{
                      color: "var(--ink-3)",
                      margin: 0,
                    }}
                  >
                    {member.role}
                  </p>

                  <p
                    style={{
                      fontFamily: "var(--font-body)",
                      fontSize: 14,
                      fontStyle: "italic",
                      color: "var(--ink-3)",
                      lineHeight: 1.5,
                      margin: 0,
                    }}
                  >
                    {member.origin}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ═══════════════════════════════════════════════════════
            TICKET Panel — GA Orange CTA
            ═══════════════════════════════════════════════════════ */}
        <div
          className="ticket-panel"
          style={{
            position: "relative",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            textAlign: "center",
            padding: "96px 64px",
          }}
        >
          {/* Grommet circles — four corners */}
          <div
            aria-hidden="true"
            style={{
              position: "absolute",
              top: 24,
              left: 24,
              width: 16,
              height: 16,
              borderRadius: "50%",
              background: "var(--ink)",
            }}
          />
          <div
            aria-hidden="true"
            style={{
              position: "absolute",
              top: 24,
              right: 24,
              width: 16,
              height: 16,
              borderRadius: "50%",
              background: "var(--ink)",
            }}
          />
          <div
            aria-hidden="true"
            style={{
              position: "absolute",
              bottom: 24,
              left: 24,
              width: 16,
              height: 16,
              borderRadius: "50%",
              background: "var(--ink)",
            }}
          />
          <div
            aria-hidden="true"
            style={{
              position: "absolute",
              bottom: 24,
              right: 24,
              width: 16,
              height: 16,
              borderRadius: "50%",
              background: "var(--ink)",
            }}
          />

          {/* Dashed perforation top */}
          <div
            aria-hidden="true"
            style={{
              position: "absolute",
              top: 40,
              left: 48,
              right: 48,
              height: 0,
              borderTop: "2px dashed rgba(10,10,10,0.20)",
            }}
          />

          {/* Dashed perforation bottom */}
          <div
            aria-hidden="true"
            style={{
              position: "absolute",
              bottom: 40,
              left: 48,
              right: 48,
              height: 0,
              borderTop: "2px dashed rgba(10,10,10,0.20)",
            }}
          />

          {/* Headline */}
          <h2
            style={{
              fontFamily: "var(--font-hero)",
              fontStyle: "italic",
              fontWeight: 400,
              fontSize: "clamp(40px, 5vw, 56px)",
              letterSpacing: "-0.02em",
              lineHeight: 1.1,
              color: "var(--ink)",
              margin: "0 0 24px",
            }}
          >
            Our mission is
            <br />
            the walk-in.
          </h2>

          <p
            style={{
              fontFamily: "var(--font-body)",
              fontSize: 16,
              color: "var(--ink)",
              lineHeight: 1.6,
              maxWidth: 480,
              margin: "0 0 32px",
            }}
          >
            Build a business worth visiting. We&rsquo;ll find the creators
            who&rsquo;ll tell people about it.
          </p>

          {/* CTA row */}
          <div
            style={{
              display: "flex",
              gap: 16,
              flexWrap: "wrap",
              justifyContent: "center",
            }}
          >
            <Link href="/creator/signup" className="btn-ink click-shift">
              Join as Creator
            </Link>
            <Link
              href="/merchant/signup"
              className="btn-ghost click-shift"
              style={{ color: "var(--ink)", borderColor: "var(--ink)" }}
            >
              For Merchants
            </Link>
          </div>
        </div>
      </main>

      <Footer />
    </>
  );
}
