// Mock transaction data — 50+ entries
// TODO: wire to Supabase

export type TransactionStatus = "pending" | "cleared" | "processing" | "paid";

export type Transaction = {
  id: string;
  date: string;
  campaign: string;
  merchant: string;
  category: string;
  milestoneStage:
    | "accepted"
    | "visited"
    | "content_posted"
    | "verified"
    | "paid";
  status: TransactionStatus;
  amount: number;
  commissionAmount: number;
  netAmount: number;
};

export type MerchantPayment = {
  id: string;
  date: string;
  campaign: string;
  creator: string;
  status: "scheduled" | "processing" | "completed";
  amount: number;
  invoiceRef: string;
};

// Creator transactions (52 entries)
export const MOCK_CREATOR_TRANSACTIONS: Transaction[] = [
  {
    id: "txn-001",
    date: "2026-04-15",
    campaign: "Best Burger in NYC Feature",
    merchant: "Superiority Burger",
    category: "Food",
    milestoneStage: "paid",
    status: "paid",
    amount: 35,
    commissionAmount: 5.25,
    netAmount: 40.25,
  },
  {
    id: "txn-002",
    date: "2026-04-12",
    campaign: "LA Botanica Aesthetic Shoot",
    merchant: "Flamingo Estate",
    category: "Lifestyle",
    milestoneStage: "verified",
    status: "cleared",
    amount: 75,
    commissionAmount: 11.25,
    netAmount: 86.25,
  },
  {
    id: "txn-003",
    date: "2026-04-10",
    campaign: "Brow Transformation Story",
    merchant: "Brow Theory",
    category: "Beauty",
    milestoneStage: "content_posted",
    status: "processing",
    amount: 50,
    commissionAmount: 7.5,
    netAmount: 57.5,
  },
  {
    id: "txn-004",
    date: "2026-04-08",
    campaign: "Glossier NYC Store Experience",
    merchant: "Glossier",
    category: "Beauty",
    milestoneStage: "visited",
    status: "pending",
    amount: 120,
    commissionAmount: 18,
    netAmount: 138,
  },
  {
    id: "txn-005",
    date: "2026-04-05",
    campaign: "Le Bec-Fin Pop-Up Review",
    merchant: "Le Bec Fin",
    category: "Food",
    milestoneStage: "paid",
    status: "paid",
    amount: 20,
    commissionAmount: 0,
    netAmount: 20,
  },
  {
    id: "txn-006",
    date: "2026-04-02",
    campaign: "Matcha Morning Ritual",
    merchant: "Cha Cha Matcha",
    category: "Coffee",
    milestoneStage: "paid",
    status: "paid",
    amount: 25,
    commissionAmount: 3.75,
    netAmount: 28.75,
  },
  {
    id: "txn-007",
    date: "2026-03-28",
    campaign: "KITH x Creator Collab",
    merchant: "KITH",
    category: "Retail",
    milestoneStage: "paid",
    status: "paid",
    amount: 199,
    commissionAmount: 29.85,
    netAmount: 228.85,
  },
  {
    id: "txn-008",
    date: "2026-03-25",
    campaign: "Morning Ritual Campaign",
    merchant: "Blank Street Coffee",
    category: "Coffee",
    milestoneStage: "paid",
    status: "paid",
    amount: 0,
    commissionAmount: 0,
    netAmount: 0,
  },
  {
    id: "txn-009",
    date: "2026-03-22",
    campaign: "Flamingo Estate Lookbook",
    merchant: "Flamingo Estate",
    category: "Lifestyle",
    milestoneStage: "paid",
    status: "paid",
    amount: 95,
    commissionAmount: 14.25,
    netAmount: 109.25,
  },
  {
    id: "txn-010",
    date: "2026-03-18",
    campaign: "Glossier Spring Drop",
    merchant: "Glossier",
    category: "Beauty",
    milestoneStage: "paid",
    status: "paid",
    amount: 110,
    commissionAmount: 16.5,
    netAmount: 126.5,
  },
  {
    id: "txn-011",
    date: "2026-03-14",
    campaign: "SoHo Fitness Challenge",
    merchant: "Barry's Bootcamp",
    category: "Fitness",
    milestoneStage: "paid",
    status: "paid",
    amount: 60,
    commissionAmount: 9,
    netAmount: 69,
  },
  {
    id: "txn-012",
    date: "2026-03-10",
    campaign: "Nolita Brunch Spot",
    merchant: "Cafe Gitane",
    category: "Food",
    milestoneStage: "paid",
    status: "paid",
    amount: 40,
    commissionAmount: 6,
    netAmount: 46,
  },
  {
    id: "txn-013",
    date: "2026-03-06",
    campaign: "Spring Skincare Routine",
    merchant: "Aesop",
    category: "Beauty",
    milestoneStage: "paid",
    status: "paid",
    amount: 80,
    commissionAmount: 12,
    netAmount: 92,
  },
  {
    id: "txn-014",
    date: "2026-03-02",
    campaign: "LES Vintage Picks",
    merchant: "Housing Works",
    category: "Retail",
    milestoneStage: "paid",
    status: "paid",
    amount: 30,
    commissionAmount: 4.5,
    netAmount: 34.5,
  },
  {
    id: "txn-015",
    date: "2026-02-26",
    campaign: "Tribeca Wellness Walk",
    merchant: "Equinox",
    category: "Fitness",
    milestoneStage: "paid",
    status: "paid",
    amount: 75,
    commissionAmount: 11.25,
    netAmount: 86.25,
  },
  {
    id: "txn-016",
    date: "2026-02-22",
    campaign: "West Village Coffee Trail",
    merchant: "Café Regular",
    category: "Coffee",
    milestoneStage: "paid",
    status: "paid",
    amount: 20,
    commissionAmount: 3,
    netAmount: 23,
  },
  {
    id: "txn-017",
    date: "2026-02-18",
    campaign: "Brooklyn Botanical Shoot",
    merchant: "Brooklyn Botanic Garden",
    category: "Lifestyle",
    milestoneStage: "paid",
    status: "paid",
    amount: 65,
    commissionAmount: 9.75,
    netAmount: 74.75,
  },
  {
    id: "txn-018",
    date: "2026-02-14",
    campaign: "Valentine's Day Dining",
    merchant: "Lilia",
    category: "Food",
    milestoneStage: "paid",
    status: "paid",
    amount: 90,
    commissionAmount: 13.5,
    netAmount: 103.5,
  },
  {
    id: "txn-019",
    date: "2026-02-10",
    campaign: "Studio Yoga Series",
    merchant: "Y7 Studio",
    category: "Fitness",
    milestoneStage: "paid",
    status: "paid",
    amount: 45,
    commissionAmount: 6.75,
    netAmount: 51.75,
  },
  {
    id: "txn-020",
    date: "2026-02-06",
    campaign: "Bushwick Art Walk",
    merchant: "Pioneer Works",
    category: "Lifestyle",
    milestoneStage: "paid",
    status: "paid",
    amount: 55,
    commissionAmount: 8.25,
    netAmount: 63.25,
  },
  {
    id: "txn-021",
    date: "2026-02-02",
    campaign: "Hudson Yards Style Drop",
    merchant: "Zara NYC",
    category: "Retail",
    milestoneStage: "paid",
    status: "paid",
    amount: 70,
    commissionAmount: 10.5,
    netAmount: 80.5,
  },
  {
    id: "txn-022",
    date: "2026-01-28",
    campaign: "Chelsea Market Taste Test",
    merchant: "Chelsea Market",
    category: "Food",
    milestoneStage: "paid",
    status: "paid",
    amount: 50,
    commissionAmount: 7.5,
    netAmount: 57.5,
  },
  {
    id: "txn-023",
    date: "2026-01-24",
    campaign: "Flatiron Cold Brew Review",
    merchant: "Blue Bottle Coffee",
    category: "Coffee",
    milestoneStage: "paid",
    status: "paid",
    amount: 30,
    commissionAmount: 4.5,
    netAmount: 34.5,
  },
  {
    id: "txn-024",
    date: "2026-01-20",
    campaign: "UWS Health Routine",
    merchant: "Whole Foods",
    category: "Lifestyle",
    milestoneStage: "paid",
    status: "paid",
    amount: 40,
    commissionAmount: 6,
    netAmount: 46,
  },
  {
    id: "txn-025",
    date: "2026-01-16",
    campaign: "SoHo x Kiehl's Collab",
    merchant: "Kiehl's",
    category: "Beauty",
    milestoneStage: "paid",
    status: "paid",
    amount: 85,
    commissionAmount: 12.75,
    netAmount: 97.75,
  },
  {
    id: "txn-026",
    date: "2026-01-12",
    campaign: "NoLIta Food Walk",
    merchant: "Rubirosa",
    category: "Food",
    milestoneStage: "paid",
    status: "paid",
    amount: 35,
    commissionAmount: 5.25,
    netAmount: 40.25,
  },
  {
    id: "txn-027",
    date: "2026-01-08",
    campaign: "Dumbo Vintage Market",
    merchant: "Artists & Fleas",
    category: "Retail",
    milestoneStage: "paid",
    status: "paid",
    amount: 25,
    commissionAmount: 3.75,
    netAmount: 28.75,
  },
  {
    id: "txn-028",
    date: "2026-01-04",
    campaign: "New Year Pilates",
    merchant: "SLT",
    category: "Fitness",
    milestoneStage: "paid",
    status: "paid",
    amount: 55,
    commissionAmount: 8.25,
    netAmount: 63.25,
  },
  {
    id: "txn-029",
    date: "2025-12-28",
    campaign: "Holiday Market Shoot",
    merchant: "Union Square Market",
    category: "Lifestyle",
    milestoneStage: "paid",
    status: "paid",
    amount: 60,
    commissionAmount: 9,
    netAmount: 69,
  },
  {
    id: "txn-030",
    date: "2025-12-24",
    campaign: "Christmas Dinner Review",
    merchant: "Carbone",
    category: "Food",
    milestoneStage: "paid",
    status: "paid",
    amount: 150,
    commissionAmount: 22.5,
    netAmount: 172.5,
  },
  {
    id: "txn-031",
    date: "2025-12-20",
    campaign: "Winter Matcha Campaign",
    merchant: "Cha Cha Matcha",
    category: "Coffee",
    milestoneStage: "paid",
    status: "paid",
    amount: 25,
    commissionAmount: 3.75,
    netAmount: 28.75,
  },
  {
    id: "txn-032",
    date: "2025-12-16",
    campaign: "Midtown Beauty Haul",
    merchant: "Sephora",
    category: "Beauty",
    milestoneStage: "paid",
    status: "paid",
    amount: 95,
    commissionAmount: 14.25,
    netAmount: 109.25,
  },
  {
    id: "txn-033",
    date: "2025-12-12",
    campaign: "Brooklyn Yoga Retreat",
    merchant: "Modo Yoga",
    category: "Fitness",
    milestoneStage: "paid",
    status: "paid",
    amount: 70,
    commissionAmount: 10.5,
    netAmount: 80.5,
  },
  {
    id: "txn-034",
    date: "2025-12-08",
    campaign: "Park Slope Cafe Crawl",
    merchant: "Hungry Ghost",
    category: "Coffee",
    milestoneStage: "paid",
    status: "paid",
    amount: 20,
    commissionAmount: 3,
    netAmount: 23,
  },
  {
    id: "txn-035",
    date: "2025-12-04",
    campaign: "Greenpoint Art Festival",
    merchant: "Silent Barn",
    category: "Lifestyle",
    milestoneStage: "paid",
    status: "paid",
    amount: 80,
    commissionAmount: 12,
    netAmount: 92,
  },
  {
    id: "txn-036",
    date: "2025-11-30",
    campaign: "Black Friday Streetwear",
    merchant: "Supreme",
    category: "Retail",
    milestoneStage: "paid",
    status: "paid",
    amount: 200,
    commissionAmount: 30,
    netAmount: 230,
  },
  {
    id: "txn-037",
    date: "2025-11-26",
    campaign: "Thanksgiving Dining Feature",
    merchant: "Momofuku",
    category: "Food",
    milestoneStage: "paid",
    status: "paid",
    amount: 100,
    commissionAmount: 15,
    netAmount: 115,
  },
  {
    id: "txn-038",
    date: "2025-11-22",
    campaign: "UES Luxury Skincare",
    merchant: "La Mer",
    category: "Beauty",
    milestoneStage: "paid",
    status: "paid",
    amount: 160,
    commissionAmount: 24,
    netAmount: 184,
  },
  {
    id: "txn-039",
    date: "2025-11-18",
    campaign: "Autumn Yoga Challenge",
    merchant: "CorePower",
    category: "Fitness",
    milestoneStage: "paid",
    status: "paid",
    amount: 50,
    commissionAmount: 7.5,
    netAmount: 57.5,
  },
  {
    id: "txn-040",
    date: "2025-11-14",
    campaign: "Brooklyn Brewery Tour",
    merchant: "Brooklyn Brewery",
    category: "Food",
    milestoneStage: "paid",
    status: "paid",
    amount: 45,
    commissionAmount: 6.75,
    netAmount: 51.75,
  },
  {
    id: "txn-041",
    date: "2025-11-10",
    campaign: "Astoria Coffee Scene",
    merchant: "Coffeed",
    category: "Coffee",
    milestoneStage: "paid",
    status: "paid",
    amount: 30,
    commissionAmount: 4.5,
    netAmount: 34.5,
  },
  {
    id: "txn-042",
    date: "2025-11-06",
    campaign: "FiDi Lunch Spot",
    merchant: "Sweetgreen",
    category: "Food",
    milestoneStage: "paid",
    status: "paid",
    amount: 20,
    commissionAmount: 3,
    netAmount: 23,
  },
  {
    id: "txn-043",
    date: "2025-11-02",
    campaign: "Williamsburg Style Guide",
    merchant: "Pilgrim Surf + Supply",
    category: "Retail",
    milestoneStage: "paid",
    status: "paid",
    amount: 90,
    commissionAmount: 13.5,
    netAmount: 103.5,
  },
  {
    id: "txn-044",
    date: "2025-10-28",
    campaign: "Halloween Beauty Collab",
    merchant: "MAC Cosmetics",
    category: "Beauty",
    milestoneStage: "paid",
    status: "paid",
    amount: 75,
    commissionAmount: 11.25,
    netAmount: 86.25,
  },
  {
    id: "txn-045",
    date: "2025-10-24",
    campaign: "CrossFit Open Feature",
    merchant: "CrossFit NYC",
    category: "Fitness",
    milestoneStage: "paid",
    status: "paid",
    amount: 65,
    commissionAmount: 9.75,
    netAmount: 74.75,
  },
  {
    id: "txn-046",
    date: "2025-10-20",
    campaign: "Prospect Park Picnic",
    merchant: "Dig Inn",
    category: "Food",
    milestoneStage: "paid",
    status: "paid",
    amount: 35,
    commissionAmount: 5.25,
    netAmount: 40.25,
  },
  {
    id: "txn-047",
    date: "2025-10-16",
    campaign: "Lower East Side Espresso",
    merchant: "Variety Coffee",
    category: "Coffee",
    milestoneStage: "paid",
    status: "paid",
    amount: 20,
    commissionAmount: 3,
    netAmount: 23,
  },
  {
    id: "txn-048",
    date: "2025-10-12",
    campaign: "Autumn Capsule Wardrobe",
    merchant: "Uniqlo",
    category: "Retail",
    milestoneStage: "paid",
    status: "paid",
    amount: 55,
    commissionAmount: 8.25,
    netAmount: 63.25,
  },
  {
    id: "txn-049",
    date: "2025-10-08",
    campaign: "Red Hook Waterfront Shoot",
    merchant: "Fort Defiance",
    category: "Lifestyle",
    milestoneStage: "paid",
    status: "paid",
    amount: 70,
    commissionAmount: 10.5,
    netAmount: 80.5,
  },
  {
    id: "txn-050",
    date: "2025-10-04",
    campaign: "Manhattan Brow Studio",
    merchant: "Brow Code",
    category: "Beauty",
    milestoneStage: "paid",
    status: "paid",
    amount: 55,
    commissionAmount: 8.25,
    netAmount: 63.25,
  },
  {
    id: "txn-051",
    date: "2025-09-30",
    campaign: "Chelsea Gallery Walk",
    merchant: "Gagosian",
    category: "Lifestyle",
    milestoneStage: "paid",
    status: "paid",
    amount: 100,
    commissionAmount: 15,
    netAmount: 115,
  },
  {
    id: "txn-052",
    date: "2025-09-26",
    campaign: "Greenpoint Specialty Brew",
    merchant: "Cafe Grumpy",
    category: "Coffee",
    milestoneStage: "paid",
    status: "paid",
    amount: 25,
    commissionAmount: 3.75,
    netAmount: 28.75,
  },
];

// Merchant payment records
export const MOCK_MERCHANT_PAYMENTS: MerchantPayment[] = [
  {
    id: "mpay-001",
    date: "2026-04-30",
    campaign: "LA Botanica Aesthetic Shoot",
    creator: "Alex Chen",
    status: "scheduled",
    amount: 86.25,
    invoiceRef: "INV-2026-04-001",
  },
  {
    id: "mpay-002",
    date: "2026-04-28",
    campaign: "Brow Transformation Story",
    creator: "Maya Rodriguez",
    status: "scheduled",
    amount: 57.5,
    invoiceRef: "INV-2026-04-002",
  },
  {
    id: "mpay-003",
    date: "2026-04-20",
    campaign: "Morning Ritual Campaign",
    creator: "James Park",
    status: "processing",
    amount: 40.25,
    invoiceRef: "INV-2026-04-003",
  },
  {
    id: "mpay-004",
    date: "2026-04-18",
    campaign: "Matcha Morning Ritual",
    creator: "Sofia Chen",
    status: "processing",
    amount: 28.75,
    invoiceRef: "INV-2026-04-004",
  },
  {
    id: "mpay-005",
    date: "2026-04-15",
    campaign: "Best Burger in NYC Feature",
    creator: "Alex Chen",
    status: "completed",
    amount: 40.25,
    invoiceRef: "INV-2026-04-005",
  },
  {
    id: "mpay-006",
    date: "2026-04-12",
    campaign: "Glossier NYC Store Experience",
    creator: "Lily Wang",
    status: "completed",
    amount: 138,
    invoiceRef: "INV-2026-04-006",
  },
  {
    id: "mpay-007",
    date: "2026-04-10",
    campaign: "Le Bec-Fin Pop-Up Review",
    creator: "Marcus Johnson",
    status: "completed",
    amount: 20,
    invoiceRef: "INV-2026-04-007",
  },
  {
    id: "mpay-008",
    date: "2026-04-08",
    campaign: "KITH x Creator Collab",
    creator: "Nina Torres",
    status: "completed",
    amount: 228.85,
    invoiceRef: "INV-2026-04-008",
  },
  {
    id: "mpay-009",
    date: "2026-04-05",
    campaign: "Flamingo Estate Lookbook",
    creator: "Jordan Lee",
    status: "completed",
    amount: 109.25,
    invoiceRef: "INV-2026-04-009",
  },
  {
    id: "mpay-010",
    date: "2026-04-02",
    campaign: "Morning Ritual Campaign",
    creator: "Sam Kim",
    status: "completed",
    amount: 46,
    invoiceRef: "INV-2026-04-010",
  },
];

// Monthly invoice records
export type MonthlyInvoice = {
  id: string;
  month: string;
  year: number;
  totalAmount: number;
  paymentCount: number;
  status: "available" | "pending";
  pdfRef: string;
};

export const MOCK_MONTHLY_INVOICES: MonthlyInvoice[] = [
  {
    id: "inv-2026-04",
    month: "April",
    year: 2026,
    totalAmount: 755.35,
    paymentCount: 8,
    status: "pending",
    pdfRef: "push-invoice-2026-04.pdf",
  },
  {
    id: "inv-2026-03",
    month: "March",
    year: 2026,
    totalAmount: 1240.5,
    paymentCount: 14,
    status: "available",
    pdfRef: "push-invoice-2026-03.pdf",
  },
  {
    id: "inv-2026-02",
    month: "February",
    year: 2026,
    totalAmount: 980.75,
    paymentCount: 11,
    status: "available",
    pdfRef: "push-invoice-2026-02.pdf",
  },
  {
    id: "inv-2026-01",
    month: "January",
    year: 2026,
    totalAmount: 1520,
    paymentCount: 16,
    status: "available",
    pdfRef: "push-invoice-2026-01.pdf",
  },
  {
    id: "inv-2025-12",
    month: "December",
    year: 2025,
    totalAmount: 2100.25,
    paymentCount: 22,
    status: "available",
    pdfRef: "push-invoice-2025-12.pdf",
  },
  {
    id: "inv-2025-11",
    month: "November",
    year: 2025,
    totalAmount: 1875,
    paymentCount: 19,
    status: "available",
    pdfRef: "push-invoice-2025-11.pdf",
  },
];
