import type { Creator, Campaign, Application, Payout } from "./types";

export const DEMO_CREATOR: Creator = {
  id: "demo-creator-001",
  name: "Alex Chen",
  instagram_handle: "alexcheneats",
  location: "Lower East Side, NYC",
  bio: "NYC food & lifestyle creator. Always hunting for the next hidden gem.",
  tier: "operator",
  push_score: 71,
  campaigns_completed: 12,
  campaigns_accepted: 14,
  earnings_total: 130,
  earnings_pending: 75,
  instagram_followers: 4200,
};

export const DEMO_CAMPAIGNS: Campaign[] = [
  {
    id: "camp-001",
    title: "Morning Ritual Campaign",
    business_name: "Blank Street Coffee",
    business_address: "5 W 19th St, New York, NY 10011",
    payout: 0,
    spots_remaining: 12,
    spots_total: 20,
    deadline: "2026-04-30",
    category: "Coffee",
    tier_required: "seed",
    description:
      "Visit any Blank Street location, enjoy a drink, and share your experience. Perfect for building your portfolio.",
    requirements: [
      "1 Instagram story tagging @blankstreetcoffee",
      "Visit during peak hours (7-10am)",
    ],
    lat: 40.7395,
    lng: -73.994,
  },
  {
    id: "camp-002",
    title: "Best Burger in NYC Feature",
    business_name: "Superiority Burger",
    business_address: "119 Avenue A, New York, NY 10009",
    payout: 35,
    spots_remaining: 4,
    spots_total: 8,
    deadline: "2026-04-25",
    category: "Food",
    tier_required: "explorer",
    description:
      "Feature our award-winning veggie burgers in an authentic review.",
    requirements: [
      "1 Instagram Reel (min 30s)",
      "Tag @superiorityburger",
      "Must include the Classic Burger",
    ],
    lat: 40.726,
    lng: -73.9831,
  },
  {
    id: "camp-003",
    title: "LA Botanica Aesthetic Shoot",
    business_name: "Flamingo Estate",
    business_address: "La Guardia Pl, New York, NY 10012",
    payout: 75,
    spots_remaining: 3,
    spots_total: 6,
    deadline: "2026-05-05",
    category: "Lifestyle",
    tier_required: "operator",
    description:
      "Capture the Flamingo Estate aesthetic at our NYC pop-up. Moody, editorial, nature-forward content.",
    requirements: [
      "2 feed posts + 3 stories",
      "Aesthetic must match brand guidelines (provided)",
      "Submit content for approval 48h before posting",
    ],
    lat: 40.7291,
    lng: -74.0018,
  },
  {
    id: "camp-004",
    title: "Brow Transformation Story",
    business_name: "Brow Theory",
    business_address: "247 Centre St, New York, NY 10013",
    payout: 50,
    spots_remaining: 5,
    spots_total: 10,
    deadline: "2026-04-28",
    category: "Beauty",
    tier_required: "explorer",
    description:
      "Document your brow transformation at Brow Theory. Before/after content preferred.",
    requirements: [
      "Before & after Instagram stories",
      "1 feed post or Reel",
      "Tag @browtheorynyc",
    ],
    lat: 40.7195,
    lng: -74.0018,
  },
  {
    id: "camp-005",
    title: "Glossier NYC Store Experience",
    business_name: "Glossier",
    business_address: "1a York Ave, New York, NY 10065",
    payout: 120,
    spots_remaining: 2,
    spots_total: 5,
    deadline: "2026-05-10",
    category: "Beauty",
    tier_required: "proven",
    description:
      "Create editorial beauty content at the Glossier flagship. High production value expected.",
    requirements: [
      "3+ feed posts",
      "Dedicated YouTube or TikTok video (min 3 min)",
      "Engagement rate > 3%",
    ],
    lat: 40.7625,
    lng: -73.9577,
  },
  {
    id: "camp-006",
    title: "Le Bec-Fin Pop-Up Review",
    business_name: "Le Bec Fin",
    business_address: "1 Rockefeller Plaza, New York, NY 10020",
    payout: 20,
    spots_remaining: 8,
    spots_total: 15,
    deadline: "2026-04-22",
    category: "Food",
    tier_required: "seed",
    description:
      "Try the NYC pop-up of the legendary Philadelphia institution. Share an honest review.",
    requirements: ["1 Instagram story or post", "Tag location"],
    lat: 40.7597,
    lng: -73.9787,
  },
  {
    id: "camp-007",
    title: "KITH x Creator Collab Series",
    business_name: "KITH",
    business_address: "337 Lafayette St, New York, NY 10012",
    payout: 199,
    spots_remaining: 1,
    spots_total: 3,
    deadline: "2026-05-15",
    category: "Retail",
    tier_required: "proven",
    description:
      "Exclusive creator collab at KITH SoHo. Style editorial campaign for Spring 2026 collection.",
    requirements: [
      "5+ high-quality feed posts",
      "2 Reels",
      "10k+ Instagram followers required",
      "Portfolio review required",
    ],
    lat: 40.7248,
    lng: -74.0012,
  },
  {
    id: "camp-008",
    title: "Matcha Morning Ritual",
    business_name: "Cha Cha Matcha",
    business_address: "373 Broadway, New York, NY 10013",
    payout: 25,
    spots_remaining: 6,
    spots_total: 12,
    deadline: "2026-04-29",
    category: "Coffee",
    tier_required: "seed",
    description:
      "Share your morning matcha ritual at Cha Cha Matcha. Aesthetic, cozy content welcome.",
    requirements: ["2 Instagram stories", "Tag @chachamatcha"],
    lat: 40.7178,
    lng: -74.003,
  },
];

export const DEMO_APPLICATIONS: Application[] = [
  {
    id: "app-001",
    campaign_id: "camp-003",
    status: "accepted",
    milestone: "scheduled",
    payout: 75,
    created_at: "2026-04-05T10:00:00Z",
    campaign_title: "LA Botanica Aesthetic Shoot",
    merchant_name: "Flamingo Estate",
    deadline: "2026-05-05",
    category: "Lifestyle",
  },
  {
    id: "app-002",
    campaign_id: "camp-002",
    status: "accepted",
    milestone: "verified",
    payout: 35,
    created_at: "2026-03-20T09:00:00Z",
    campaign_title: "Best Burger in NYC Feature",
    merchant_name: "Superiority Burger",
    deadline: "2026-04-25",
    category: "Food",
  },
  {
    id: "app-003",
    campaign_id: "camp-004",
    status: "pending",
    milestone: "accepted",
    payout: 50,
    created_at: "2026-04-08T14:00:00Z",
    campaign_title: "Brow Transformation Story",
    merchant_name: "Brow Theory",
    deadline: "2026-04-28",
    category: "Beauty",
  },
  {
    id: "app-004",
    campaign_id: "camp-006",
    status: "accepted",
    milestone: "settled",
    payout: 20,
    created_at: "2026-03-10T11:00:00Z",
    campaign_title: "Le Bec-Fin Pop-Up Review",
    merchant_name: "Le Bec Fin",
    deadline: "2026-04-22",
    category: "Food",
  },
];

export const DEMO_PAYOUTS: Payout[] = [
  {
    id: "pay-001",
    campaign_title: "Le Bec-Fin Pop-Up Review",
    merchant_name: "Le Bec Fin",
    amount: 20,
    commission_amount: 0,
    payout_type: "base",
    status: "completed",
    paid_at: "2026-03-25T00:00:00Z",
    created_at: "2026-03-25T00:00:00Z",
  },
  {
    id: "pay-002",
    campaign_title: "Best Burger in NYC Feature",
    merchant_name: "Superiority Burger",
    amount: 35,
    commission_amount: 5.25,
    payout_type: "base",
    status: "completed",
    paid_at: "2026-04-02T00:00:00Z",
    created_at: "2026-04-02T00:00:00Z",
  },
  {
    id: "pay-003",
    campaign_title: "Blank Street Morning",
    merchant_name: "Blank Street Coffee",
    amount: 0,
    commission_amount: 0,
    payout_type: "base",
    status: "completed",
    paid_at: "2026-03-15T00:00:00Z",
    created_at: "2026-03-15T00:00:00Z",
  },
  {
    id: "pay-004",
    campaign_title: "LA Botanica Aesthetic Shoot",
    merchant_name: "Flamingo Estate",
    amount: 75,
    commission_amount: 11.25,
    payout_type: "base",
    status: "pending",
    paid_at: null,
    created_at: "2026-04-10T00:00:00Z",
  },
  {
    id: "pay-005",
    campaign_title: "Brow Transformation Story",
    merchant_name: "Brow Theory",
    amount: 0,
    commission_amount: 0,
    payout_type: "base",
    status: "processing",
    paid_at: null,
    created_at: "2026-04-09T00:00:00Z",
  },
];
